/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AlbumManagePageVO
 */
export interface AlbumManagePageVO {
    /**
     * 
     * @type {string}
     * @memberof AlbumManagePageVO
     */
    'createTime': string;
    /**
     * 
     * @type {number}
     * @memberof AlbumManagePageVO
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof AlbumManagePageVO
     */
    'imageCount': number;
    /**
     * 
     * @type {string}
     * @memberof AlbumManagePageVO
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof AlbumManagePageVO
     */
    'userEmail': string;
    /**
     * 
     * @type {number}
     * @memberof AlbumManagePageVO
     */
    'userId': number;
    /**
     * 
     * @type {string}
     * @memberof AlbumManagePageVO
     */
    'username': string;
}

