/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AlbumPageVO
 */
export interface AlbumPageVO {
    /**
     * 
     * @type {number}
     * @memberof AlbumPageVO
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof AlbumPageVO
     */
    imageCount: number;
    /**
     * 
     * @type {boolean}
     * @memberof AlbumPageVO
     */
    isUncategorized: boolean;
    /**
     * 
     * @type {string}
     * @memberof AlbumPageVO
     */
    name: string;
}

/**
 * Check if a given object implements the AlbumPageVO interface.
 */
export function instanceOfAlbumPageVO(value: object): value is AlbumPageVO {
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('imageCount' in value) || value['imageCount'] === undefined) return false;
    if (!('isUncategorized' in value) || value['isUncategorized'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function AlbumPageVOFromJSON(json: any): AlbumPageVO {
    return AlbumPageVOFromJSONTyped(json, false);
}

export function AlbumPageVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): AlbumPageVO {
    if (json == null) {
        return json;
    }
    return {
        
        'id': json['id'],
        'imageCount': json['imageCount'],
        'isUncategorized': json['isUncategorized'],
        'name': json['name'],
    };
}

  export function AlbumPageVOToJSON(json: any): AlbumPageVO {
      return AlbumPageVOToJSONTyped(json, false);
  }

  export function AlbumPageVOToJSONTyped(value?: AlbumPageVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'id': value['id'],
        'imageCount': value['imageCount'],
        'isUncategorized': value['isUncategorized'],
        'name': value['name'],
    };
}

