/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface AlbumSelfInsertRequest
 */
export interface AlbumSelfInsertRequest {
    /**
     * 
     * @type {string}
     * @memberof AlbumSelfInsertRequest
     */
    'description': string;
    /**
     * 
     * @type {string}
     * @memberof AlbumSelfInsertRequest
     */
    'name': string;
}

