/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * @type ApiImageImageIdGet200Response
 * 
 * @export
 */
export type ApiImageImageIdGet200Response = string;

export function ApiImageImageIdGet200ResponseFromJSON(json: any): ApiImageImageIdGet200Response {
    return ApiImageImageIdGet200ResponseFromJSONTyped(json, false);
}

export function ApiImageImageIdGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiImageImageIdGet200Response {
    if (json == null) {
        return json;
    }
    if (instanceOfstring(json)) {
        return stringFromJSONTyped(json, true);
    }

    return {} as any;
}

export function ApiImageImageIdGet200ResponseToJSON(value?: ApiImageImageIdGet200Response | null): any {
    if (value == null) {
        return value;
    }

    if (instanceOfstring(value)) {
        return stringToJSON(value as string);
    }

    return {};
}

