/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiStrategyPostRequest
 */
export interface ApiStrategyPostRequest {
    /**
     * io/sakurasou/model/strategy/StrategyConfig.kt
     * @type {}
     * @memberof ApiStrategyPostRequest
     */
    config?:  | null;
    /**
     * 
     * @type {string}
     * @memberof ApiStrategyPostRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the ApiStrategyPostRequest interface.
 */
export function instanceOfApiStrategyPostRequest(value: object): value is ApiStrategyPostRequest {
    return true;
}

export function ApiStrategyPostRequestFromJSON(json: any): ApiStrategyPostRequest {
    return ApiStrategyPostRequestFromJSONTyped(json, false);
}

export function ApiStrategyPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiStrategyPostRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : FromJSON(json['config']),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function ApiStrategyPostRequestToJSON(value?: ApiStrategyPostRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'config': ToJSON(value['config']),
        'name': value['name'],
    };
}

