/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupAllowedImageType } from './GroupAllowedImageType';
import {
    GroupAllowedImageTypeFromJSON,
    GroupAllowedImageTypeFromJSONTyped,
    GroupAllowedImageTypeToJSON,
    GroupAllowedImageTypeToJSONTyped,
} from './GroupAllowedImageType';

/**
 * 
 * @export
 * @interface CommonResponseGroupAllowedImageType
 */
export interface CommonResponseGroupAllowedImageType {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseGroupAllowedImageType
     */
    code: number;
    /**
     * 
     * @type {GroupAllowedImageType}
     * @memberof CommonResponseGroupAllowedImageType
     */
    data?: GroupAllowedImageType | null;
    /**
     * 
     * @type {boolean}
     * @memberof CommonResponseGroupAllowedImageType
     */
    isSuccessful: boolean;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseGroupAllowedImageType
     */
    message: string;
}

/**
 * Check if a given object implements the CommonResponseGroupAllowedImageType interface.
 */
export function instanceOfCommonResponseGroupAllowedImageType(value: object): value is CommonResponseGroupAllowedImageType {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('isSuccessful' in value) || value['isSuccessful'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseGroupAllowedImageTypeFromJSON(json: any): CommonResponseGroupAllowedImageType {
    return CommonResponseGroupAllowedImageTypeFromJSONTyped(json, false);
}

export function CommonResponseGroupAllowedImageTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseGroupAllowedImageType {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'data': json['data'] == null ? undefined : GroupAllowedImageTypeFromJSON(json['data']),
        'isSuccessful': json['isSuccessful'],
        'message': json['message'],
    };
}

  export function CommonResponseGroupAllowedImageTypeToJSON(json: any): CommonResponseGroupAllowedImageType {
      return CommonResponseGroupAllowedImageTypeToJSONTyped(json, false);
  }

  export function CommonResponseGroupAllowedImageTypeToJSONTyped(value?: CommonResponseGroupAllowedImageType | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': GroupAllowedImageTypeToJSON(value['data']),
        'isSuccessful': value['isSuccessful'],
        'message': value['message'],
    };
}

