/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CommonResponseKotlinString
 */
export interface CommonResponseKotlinString {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseKotlinString
     */
    code: number;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseKotlinString
     */
    data?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof CommonResponseKotlinString
     */
    isSuccessful: boolean;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseKotlinString
     */
    message: string;
}

/**
 * Check if a given object implements the CommonResponseKotlinString interface.
 */
export function instanceOfCommonResponseKotlinString(value: object): value is CommonResponseKotlinString {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('isSuccessful' in value) || value['isSuccessful'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseKotlinStringFromJSON(json: any): CommonResponseKotlinString {
    return CommonResponseKotlinStringFromJSONTyped(json, false);
}

export function CommonResponseKotlinStringFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseKotlinString {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'data': json['data'] == null ? undefined : json['data'],
        'isSuccessful': json['isSuccessful'],
        'message': json['message'],
    };
}

  export function CommonResponseKotlinStringToJSON(json: any): CommonResponseKotlinString {
      return CommonResponseKotlinStringToJSONTyped(json, false);
  }

  export function CommonResponseKotlinStringToJSONTyped(value?: CommonResponseKotlinString | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': value['data'],
        'isSuccessful': value['isSuccessful'],
        'message': value['message'],
    };
}

