/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { AlbumVO } from './AlbumVO';
import {
    AlbumVOFromJSON,
    AlbumVOFromJSONTyped,
    AlbumVOToJSON,
    AlbumVOToJSONTyped,
} from './AlbumVO';

/**
 * 
 * @export
 * @interface CommonResponseAlbumVO
 */
export interface CommonResponseAlbumVO {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseAlbumVO
     */
    code: number;
    /**
     * 
     * @type {AlbumVO}
     * @memberof CommonResponseAlbumVO
     */
    data?: AlbumVO | null;
    /**
     * 
     * @type {boolean}
     * @memberof CommonResponseAlbumVO
     */
    isSuccessful: boolean;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseAlbumVO
     */
    message: string;
}

/**
 * Check if a given object implements the CommonResponseAlbumVO interface.
 */
export function instanceOfCommonResponseAlbumVO(value: object): value is CommonResponseAlbumVO {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('isSuccessful' in value) || value['isSuccessful'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponseAlbumVOFromJSON(json: any): CommonResponseAlbumVO {
    return CommonResponseAlbumVOFromJSONTyped(json, false);
}

export function CommonResponseAlbumVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponseAlbumVO {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'data': json['data'] == null ? undefined : AlbumVOFromJSON(json['data']),
        'isSuccessful': json['isSuccessful'],
        'message': json['message'],
    };
}

  export function CommonResponseAlbumVOToJSON(json: any): CommonResponseAlbumVO {
      return CommonResponseAlbumVOToJSONTyped(json, false);
  }

  export function CommonResponseAlbumVOToJSONTyped(value?: CommonResponseAlbumVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': AlbumVOToJSON(value['data']),
        'isSuccessful': value['isSuccessful'],
        'message': value['message'],
    };
}

