/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StrategyVO } from './strategy-vo';

/**
 * 
 * @export
 * @interface CommonResponseStrategyVO
 */
export interface CommonResponseStrategyVO {
    /**
     * 
     * @type {number}
     * @memberof CommonResponseStrategyVO
     */
    'code': number;
    /**
     * 
     * @type {StrategyVO}
     * @memberof CommonResponseStrategyVO
     */
    'data'?: StrategyVO | null;
    /**
     * 
     * @type {boolean}
     * @memberof CommonResponseStrategyVO
     */
    'isSuccessful': boolean;
    /**
     * 
     * @type {string}
     * @memberof CommonResponseStrategyVO
     */
    'message': string;
}

