/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CommonResponseSettingVOMap
 */
export interface CommonResponseSettingVOMap {
    /**
     * 
     * @type {any}
     * @memberof CommonResponseSettingVOMap
     */
    'code'?: any;
    /**
     * 
     * @type {any}
     * @memberof CommonResponseSettingVOMap
     */
    'message'?: any;
    /**
     * 
     * @type {{ [key: string]: any; }}
     * @memberof CommonResponseSettingVOMap
     */
    'data'?: { [key: string]: any; };
    /**
     * 
     * @type {any}
     * @memberof CommonResponseSettingVOMap
     */
    'isSuccessful'?: any;
}

