/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PageResultStrategyPageVO } from './PageResultStrategyPageVO';
import {
    PageResultStrategyPageVOFromJSON,
    PageResultStrategyPageVOFromJSONTyped,
    PageResultStrategyPageVOToJSON,
    PageResultStrategyPageVOToJSONTyped,
} from './PageResultStrategyPageVO';

/**
 * 
 * @export
 * @interface CommonResponsePageResultStrategyPageVO
 */
export interface CommonResponsePageResultStrategyPageVO {
    /**
     * 
     * @type {number}
     * @memberof CommonResponsePageResultStrategyPageVO
     */
    code: number;
    /**
     * 
     * @type {PageResultStrategyPageVO}
     * @memberof CommonResponsePageResultStrategyPageVO
     */
    data?: PageResultStrategyPageVO | null;
    /**
     * 
     * @type {boolean}
     * @memberof CommonResponsePageResultStrategyPageVO
     */
    isSuccessful: boolean;
    /**
     * 
     * @type {string}
     * @memberof CommonResponsePageResultStrategyPageVO
     */
    message: string;
}

/**
 * Check if a given object implements the CommonResponsePageResultStrategyPageVO interface.
 */
export function instanceOfCommonResponsePageResultStrategyPageVO(value: object): value is CommonResponsePageResultStrategyPageVO {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('isSuccessful' in value) || value['isSuccessful'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function CommonResponsePageResultStrategyPageVOFromJSON(json: any): CommonResponsePageResultStrategyPageVO {
    return CommonResponsePageResultStrategyPageVOFromJSONTyped(json, false);
}

export function CommonResponsePageResultStrategyPageVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): CommonResponsePageResultStrategyPageVO {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'data': json['data'] == null ? undefined : PageResultStrategyPageVOFromJSON(json['data']),
        'isSuccessful': json['isSuccessful'],
        'message': json['message'],
    };
}

  export function CommonResponsePageResultStrategyPageVOToJSON(json: any): CommonResponsePageResultStrategyPageVO {
      return CommonResponsePageResultStrategyPageVOToJSONTyped(json, false);
  }

  export function CommonResponsePageResultStrategyPageVOToJSONTyped(value?: CommonResponsePageResultStrategyPageVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'code': value['code'],
        'data': PageResultStrategyPageVOToJSON(value['data']),
        'isSuccessful': value['isSuccessful'],
        'message': value['message'],
    };
}

