/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GroupPageVO
 */
export interface GroupPageVO {
    /**
     * 
     * @type {string}
     * @memberof GroupPageVO
     */
    'createTime': string;
    /**
     * 
     * @type {number}
     * @memberof GroupPageVO
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof GroupPageVO
     */
    'imageCount': number;
    /**
     * 
     * @type {number}
     * @memberof GroupPageVO
     */
    'imageSize': number;
    /**
     * 
     * @type {boolean}
     * @memberof GroupPageVO
     */
    'isSystemReserved': boolean;
    /**
     * 
     * @type {string}
     * @memberof GroupPageVO
     */
    'name': string;
    /**
     * 
     * @type {number}
     * @memberof GroupPageVO
     */
    'strategyId': number;
    /**
     * 
     * @type {string}
     * @memberof GroupPageVO
     */
    'strategyName': string;
    /**
     * 
     * @type {number}
     * @memberof GroupPageVO
     */
    'userCount': number;
}

