/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GroupConfig } from './GroupConfig';
import {
    GroupConfigFromJSON,
    GroupConfigFromJSONTyped,
    GroupConfigToJSON,
    GroupConfigToJSONTyped,
} from './GroupConfig';

/**
 * 
 * @export
 * @interface GroupVO
 */
export interface GroupVO {
    /**
     * 
     * @type {string}
     * @memberof GroupVO
     */
    description?: string | null;
    /**
     * 
     * @type {GroupConfig}
     * @memberof GroupVO
     */
    groupConfig: GroupConfig;
    /**
     * 
     * @type {number}
     * @memberof GroupVO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof GroupVO
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof GroupVO
     */
    roles: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof GroupVO
     */
    strategyId: number;
}

/**
 * Check if a given object implements the GroupVO interface.
 */
export function instanceOfGroupVO(value: object): value is GroupVO {
    if (!('groupConfig' in value) || value['groupConfig'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    if (!('strategyId' in value) || value['strategyId'] === undefined) return false;
    return true;
}

export function GroupVOFromJSON(json: any): GroupVO {
    return GroupVOFromJSONTyped(json, false);
}

export function GroupVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): GroupVO {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'groupConfig': GroupConfigFromJSON(json['groupConfig']),
        'id': json['id'],
        'name': json['name'],
        'roles': json['roles'],
        'strategyId': json['strategyId'],
    };
}

  export function GroupVOToJSON(json: any): GroupVO {
      return GroupVOToJSONTyped(json, false);
  }

  export function GroupVOToJSONTyped(value?: GroupVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'groupConfig': GroupConfigToJSON(value['groupConfig']),
        'id': value['id'],
        'name': value['name'],
        'roles': value['roles'],
        'strategyId': value['strategyId'],
    };
}

