/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KotlinByteArray } from './KotlinByteArray';
import {
    KotlinByteArrayFromJSON,
    KotlinByteArrayFromJSONTyped,
    KotlinByteArrayToJSON,
    KotlinByteArrayToJSONTyped,
} from './KotlinByteArray';

/**
 * 
 * @export
 * @interface ImageFileVO
 */
export interface ImageFileVO {
    /**
     * 
     * @type {KotlinByteArray}
     * @memberof ImageFileVO
     */
    bytes?: KotlinByteArray | null;
    /**
     * 
     * @type {string}
     * @memberof ImageFileVO
     */
    url?: string | null;
}

/**
 * Check if a given object implements the ImageFileVO interface.
 */
export function instanceOfImageFileVO(value: object): value is ImageFileVO {
    return true;
}

export function ImageFileVOFromJSON(json: any): ImageFileVO {
    return ImageFileVOFromJSONTyped(json, false);
}

export function ImageFileVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageFileVO {
    if (json == null) {
        return json;
    }
    return {
        
        'bytes': json['bytes'] == null ? undefined : KotlinByteArrayFromJSON(json['bytes']),
        'url': json['url'] == null ? undefined : json['url'],
    };
}

  export function ImageFileVOToJSON(json: any): ImageFileVO {
      return ImageFileVOToJSONTyped(json, false);
  }

  export function ImageFileVOToJSONTyped(value?: ImageFileVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'bytes': KotlinByteArrayToJSON(value['bytes']),
        'url': value['url'],
    };
}

