/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { KotlinByteArray } from './kotlin-byte-array';

/**
 * 
 * @export
 * @interface ImageFileVO
 */
export interface ImageFileVO {
    /**
     * 
     * @type {KotlinByteArray}
     * @memberof ImageFileVO
     */
    'bytes'?: KotlinByteArray | null;
    /**
     * 
     * @type {string}
     * @memberof ImageFileVO
     */
    'url'?: string | null;
}

