/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ImageManageVO
 */
export interface ImageManageVO {
    /**
     * 
     * @type {number}
     * @memberof ImageManageVO
     */
    'albumId': number;
    /**
     * 
     * @type {string}
     * @memberof ImageManageVO
     */
    'albumName': string;
    /**
     * 
     * @type {string}
     * @memberof ImageManageVO
     */
    'createTime': string;
    /**
     * 
     * @type {string}
     * @memberof ImageManageVO
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ImageManageVO
     */
    'displayName': string;
    /**
     * 
     * @type {number}
     * @memberof ImageManageVO
     */
    'groupId': number;
    /**
     * 
     * @type {string}
     * @memberof ImageManageVO
     */
    'groupName': string;
    /**
     * 
     * @type {number}
     * @memberof ImageManageVO
     */
    'height': number;
    /**
     * 
     * @type {number}
     * @memberof ImageManageVO
     */
    'id': number;
    /**
     * 
     * @type {boolean}
     * @memberof ImageManageVO
     */
    'isAllowedRandomFetch': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof ImageManageVO
     */
    'isPrivate': boolean;
    /**
     * 
     * @type {string}
     * @memberof ImageManageVO
     */
    'md5': string;
    /**
     * 
     * @type {string}
     * @memberof ImageManageVO
     */
    'mimeType': string;
    /**
     * 
     * @type {string}
     * @memberof ImageManageVO
     */
    'originName': string;
    /**
     * 
     * @type {number}
     * @memberof ImageManageVO
     */
    'ownerId': number;
    /**
     * 
     * @type {string}
     * @memberof ImageManageVO
     */
    'ownerName': string;
    /**
     * 
     * @type {string}
     * @memberof ImageManageVO
     */
    'sha256': string;
    /**
     * 
     * @type {number}
     * @memberof ImageManageVO
     */
    'size': number;
    /**
     * 
     * @type {number}
     * @memberof ImageManageVO
     */
    'strategyId': number;
    /**
     * 
     * @type {string}
     * @memberof ImageManageVO
     */
    'strategyName': string;
    /**
     * 
     * @type {string}
     * @memberof ImageManageVO
     */
    'strategyType': string;
    /**
     * 
     * @type {number}
     * @memberof ImageManageVO
     */
    'width': number;
}

