/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IoSakurasouControllerRequestGroupInsertRequest
 */
export interface IoSakurasouControllerRequestGroupInsertRequest {
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerRequestGroupInsertRequest
     */
    description?: string;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerRequestGroupInsertRequest
     */
    maxSize: number;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerRequestGroupInsertRequest
     */
    name: string;
    /**
     * 
     * @type {Array<number>}
     * @memberof IoSakurasouControllerRequestGroupInsertRequest
     */
    roles: Array<number>;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerRequestGroupInsertRequest
     */
    strategy: number;
}

/**
 * Check if a given object implements the IoSakurasouControllerRequestGroupInsertRequest interface.
 */
export function instanceOfIoSakurasouControllerRequestGroupInsertRequest(value: object): value is IoSakurasouControllerRequestGroupInsertRequest {
    if (!('maxSize' in value) || value['maxSize'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    if (!('strategy' in value) || value['strategy'] === undefined) return false;
    return true;
}

export function IoSakurasouControllerRequestGroupInsertRequestFromJSON(json: any): IoSakurasouControllerRequestGroupInsertRequest {
    return IoSakurasouControllerRequestGroupInsertRequestFromJSONTyped(json, false);
}

export function IoSakurasouControllerRequestGroupInsertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerRequestGroupInsertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'maxSize': json['maxSize'],
        'name': json['name'],
        'roles': json['roles'],
        'strategy': json['strategy'],
    };
}

export function IoSakurasouControllerRequestGroupInsertRequestToJSON(value?: IoSakurasouControllerRequestGroupInsertRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'maxSize': value['maxSize'],
        'name': value['name'],
        'roles': value['roles'],
        'strategy': value['strategy'],
    };
}

