/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IoSakurasouModelStrategyLocalStrategy
 */
export interface IoSakurasouModelStrategyLocalStrategy {
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouModelStrategyLocalStrategy
     */
    uploadFolder: string;
}

/**
 * Check if a given object implements the IoSakurasouModelStrategyLocalStrategy interface.
 */
export function instanceOfIoSakurasouModelStrategyLocalStrategy(value: object): value is IoSakurasouModelStrategyLocalStrategy {
    if (!('uploadFolder' in value) || value['uploadFolder'] === undefined) return false;
    return true;
}

export function IoSakurasouModelStrategyLocalStrategyFromJSON(json: any): IoSakurasouModelStrategyLocalStrategy {
    return IoSakurasouModelStrategyLocalStrategyFromJSONTyped(json, false);
}

export function IoSakurasouModelStrategyLocalStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouModelStrategyLocalStrategy {
    if (json == null) {
        return json;
    }
    return {
        
        'uploadFolder': json['uploadFolder'],
    };
}

export function IoSakurasouModelStrategyLocalStrategyToJSON(value?: IoSakurasouModelStrategyLocalStrategy | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'uploadFolder': value['uploadFolder'],
    };
}

