/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IoSakurasouControllerVoImageVO } from './IoSakurasouControllerVoImageVO';
import {
    IoSakurasouControllerVoImageVOFromJSON,
    IoSakurasouControllerVoImageVOFromJSONTyped,
    IoSakurasouControllerVoImageVOToJSON,
} from './IoSakurasouControllerVoImageVO';

/**
 * 
 * @export
 * @interface IoSakurasouControllerVoCommonResponseIoSakurasouControllerVoImageVO
 */
export interface IoSakurasouControllerVoCommonResponseIoSakurasouControllerVoImageVO {
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoCommonResponseIoSakurasouControllerVoImageVO
     */
    code: number;
    /**
     * 
     * @type {IoSakurasouControllerVoImageVO}
     * @memberof IoSakurasouControllerVoCommonResponseIoSakurasouControllerVoImageVO
     */
    data?: IoSakurasouControllerVoImageVO | null;
    /**
     * 
     * @type {boolean}
     * @memberof IoSakurasouControllerVoCommonResponseIoSakurasouControllerVoImageVO
     */
    isSuccessful: boolean;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerVoCommonResponseIoSakurasouControllerVoImageVO
     */
    message: string;
}

/**
 * Check if a given object implements the IoSakurasouControllerVoCommonResponseIoSakurasouControllerVoImageVO interface.
 */
export function instanceOfIoSakurasouControllerVoCommonResponseIoSakurasouControllerVoImageVO(value: object): value is IoSakurasouControllerVoCommonResponseIoSakurasouControllerVoImageVO {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('isSuccessful' in value) || value['isSuccessful'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function IoSakurasouControllerVoCommonResponseIoSakurasouControllerVoImageVOFromJSON(json: any): IoSakurasouControllerVoCommonResponseIoSakurasouControllerVoImageVO {
    return IoSakurasouControllerVoCommonResponseIoSakurasouControllerVoImageVOFromJSONTyped(json, false);
}

export function IoSakurasouControllerVoCommonResponseIoSakurasouControllerVoImageVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerVoCommonResponseIoSakurasouControllerVoImageVO {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'data': json['data'] == null ? undefined : IoSakurasouControllerVoImageVOFromJSON(json['data']),
        'isSuccessful': json['isSuccessful'],
        'message': json['message'],
    };
}

export function IoSakurasouControllerVoCommonResponseIoSakurasouControllerVoImageVOToJSON(value?: IoSakurasouControllerVoCommonResponseIoSakurasouControllerVoImageVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'data': IoSakurasouControllerVoImageVOToJSON(value['data']),
        'isSuccessful': value['isSuccessful'],
        'message': value['message'],
    };
}

