/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KotlinxDatetimeLocalDateTime } from './KotlinxDatetimeLocalDateTime';
import {
    KotlinxDatetimeLocalDateTimeFromJSON,
    KotlinxDatetimeLocalDateTimeFromJSONTyped,
    KotlinxDatetimeLocalDateTimeToJSON,
} from './KotlinxDatetimeLocalDateTime';

/**
 * 
 * @export
 * @interface IoSakurasouControllerVoUserVO
 */
export interface IoSakurasouControllerVoUserVO {
    /**
     * 
     * @type {KotlinxDatetimeLocalDateTime}
     * @memberof IoSakurasouControllerVoUserVO
     */
    createTime: KotlinxDatetimeLocalDateTime;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerVoUserVO
     */
    email: string;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerVoUserVO
     */
    groupName: string;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoUserVO
     */
    id: number;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoUserVO
     */
    imageCount: number;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoUserVO
     */
    totalImageSize: number;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerVoUserVO
     */
    username: string;
}

/**
 * Check if a given object implements the IoSakurasouControllerVoUserVO interface.
 */
export function instanceOfIoSakurasouControllerVoUserVO(value: object): value is IoSakurasouControllerVoUserVO {
    if (!('createTime' in value) || value['createTime'] === undefined) return false;
    if (!('email' in value) || value['email'] === undefined) return false;
    if (!('groupName' in value) || value['groupName'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('imageCount' in value) || value['imageCount'] === undefined) return false;
    if (!('totalImageSize' in value) || value['totalImageSize'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function IoSakurasouControllerVoUserVOFromJSON(json: any): IoSakurasouControllerVoUserVO {
    return IoSakurasouControllerVoUserVOFromJSONTyped(json, false);
}

export function IoSakurasouControllerVoUserVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerVoUserVO {
    if (json == null) {
        return json;
    }
    return {
        
        'createTime': KotlinxDatetimeLocalDateTimeFromJSON(json['createTime']),
        'email': json['email'],
        'groupName': json['groupName'],
        'id': json['id'],
        'imageCount': json['imageCount'],
        'totalImageSize': json['totalImageSize'],
        'username': json['username'],
    };
}

export function IoSakurasouControllerVoUserVOToJSON(value?: IoSakurasouControllerVoUserVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createTime': KotlinxDatetimeLocalDateTimeToJSON(value['createTime']),
        'email': value['email'],
        'groupName': value['groupName'],
        'id': value['id'],
        'imageCount': value['imageCount'],
        'totalImageSize': value['totalImageSize'],
        'username': value['username'],
    };
}

