/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IoSakurasouControllerVoAlbumVO } from './IoSakurasouControllerVoAlbumVO';
import {
    IoSakurasouControllerVoAlbumVOFromJSON,
    IoSakurasouControllerVoAlbumVOFromJSONTyped,
    IoSakurasouControllerVoAlbumVOToJSON,
} from './IoSakurasouControllerVoAlbumVO';

/**
 * 
 * @export
 * @interface IoSakurasouControllerVoCommonResponseioSakurasouControllerVoAlbumVO
 */
export interface IoSakurasouControllerVoCommonResponseioSakurasouControllerVoAlbumVO {
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoCommonResponseioSakurasouControllerVoAlbumVO
     */
    code: number;
    /**
     * 
     * @type {IoSakurasouControllerVoAlbumVO}
     * @memberof IoSakurasouControllerVoCommonResponseioSakurasouControllerVoAlbumVO
     */
    data?: IoSakurasouControllerVoAlbumVO;
    /**
     * 
     * @type {boolean}
     * @memberof IoSakurasouControllerVoCommonResponseioSakurasouControllerVoAlbumVO
     */
    isSuccessful: boolean;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerVoCommonResponseioSakurasouControllerVoAlbumVO
     */
    message: string;
}

/**
 * Check if a given object implements the IoSakurasouControllerVoCommonResponseioSakurasouControllerVoAlbumVO interface.
 */
export function instanceOfIoSakurasouControllerVoCommonResponseioSakurasouControllerVoAlbumVO(value: object): value is IoSakurasouControllerVoCommonResponseioSakurasouControllerVoAlbumVO {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('isSuccessful' in value) || value['isSuccessful'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function IoSakurasouControllerVoCommonResponseioSakurasouControllerVoAlbumVOFromJSON(json: any): IoSakurasouControllerVoCommonResponseioSakurasouControllerVoAlbumVO {
    return IoSakurasouControllerVoCommonResponseioSakurasouControllerVoAlbumVOFromJSONTyped(json, false);
}

export function IoSakurasouControllerVoCommonResponseioSakurasouControllerVoAlbumVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerVoCommonResponseioSakurasouControllerVoAlbumVO {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'data': json['data'] == null ? undefined : IoSakurasouControllerVoAlbumVOFromJSON(json['data']),
        'isSuccessful': json['isSuccessful'],
        'message': json['message'],
    };
}

export function IoSakurasouControllerVoCommonResponseioSakurasouControllerVoAlbumVOToJSON(value?: IoSakurasouControllerVoCommonResponseioSakurasouControllerVoAlbumVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'data': IoSakurasouControllerVoAlbumVOToJSON(value['data']),
        'isSuccessful': value['isSuccessful'],
        'message': value['message'],
    };
}

