/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const IoSakurasouModelStrategyStrategyType = {
    Local: 'LOCAL',
    S3: 'S3'
} as const;
export type IoSakurasouModelStrategyStrategyType = typeof IoSakurasouModelStrategyStrategyType[keyof typeof IoSakurasouModelStrategyStrategyType];


export function instanceOfIoSakurasouModelStrategyStrategyType(value: any): boolean {
    for (const key in IoSakurasouModelStrategyStrategyType) {
        if (Object.prototype.hasOwnProperty.call(IoSakurasouModelStrategyStrategyType, key)) {
            if (IoSakurasouModelStrategyStrategyType[key as keyof typeof IoSakurasouModelStrategyStrategyType] === value) {
                return true;
            }
        }
    }
    return false;
}

export function IoSakurasouModelStrategyStrategyTypeFromJSON(json: any): IoSakurasouModelStrategyStrategyType {
    return IoSakurasouModelStrategyStrategyTypeFromJSONTyped(json, false);
}

export function IoSakurasouModelStrategyStrategyTypeFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouModelStrategyStrategyType {
    return json as IoSakurasouModelStrategyStrategyType;
}

export function IoSakurasouModelStrategyStrategyTypeToJSON(value?: IoSakurasouModelStrategyStrategyType | null): any {
    return value as any;
}

