/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IoSakurasouControllerVoImagePageVO } from './IoSakurasouControllerVoImagePageVO';
import {
    IoSakurasouControllerVoImagePageVOFromJSON,
    IoSakurasouControllerVoImagePageVOFromJSONTyped,
    IoSakurasouControllerVoImagePageVOToJSON,
} from './IoSakurasouControllerVoImagePageVO';

/**
 * 
 * @export
 * @interface IoSakurasouControllerVoPageResultioSakurasouControllerVoImagePageVO
 */
export interface IoSakurasouControllerVoPageResultioSakurasouControllerVoImagePageVO {
    /**
     * 
     * @type {Array<IoSakurasouControllerVoImagePageVO>}
     * @memberof IoSakurasouControllerVoPageResultioSakurasouControllerVoImagePageVO
     */
    list: Array<IoSakurasouControllerVoImagePageVO>;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoPageResultioSakurasouControllerVoImagePageVO
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoPageResultioSakurasouControllerVoImagePageVO
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoPageResultioSakurasouControllerVoImagePageVO
     */
    total: number;
}

/**
 * Check if a given object implements the IoSakurasouControllerVoPageResultioSakurasouControllerVoImagePageVO interface.
 */
export function instanceOfIoSakurasouControllerVoPageResultioSakurasouControllerVoImagePageVO(value: object): value is IoSakurasouControllerVoPageResultioSakurasouControllerVoImagePageVO {
    if (!('list' in value) || value['list'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function IoSakurasouControllerVoPageResultioSakurasouControllerVoImagePageVOFromJSON(json: any): IoSakurasouControllerVoPageResultioSakurasouControllerVoImagePageVO {
    return IoSakurasouControllerVoPageResultioSakurasouControllerVoImagePageVOFromJSONTyped(json, false);
}

export function IoSakurasouControllerVoPageResultioSakurasouControllerVoImagePageVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerVoPageResultioSakurasouControllerVoImagePageVO {
    if (json == null) {
        return json;
    }
    return {
        
        'list': ((json['list'] as Array<any>).map(IoSakurasouControllerVoImagePageVOFromJSON)),
        'page': json['page'],
        'pageSize': json['pageSize'],
        'total': json['total'],
    };
}

export function IoSakurasouControllerVoPageResultioSakurasouControllerVoImagePageVOToJSON(value?: IoSakurasouControllerVoPageResultioSakurasouControllerVoImagePageVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'list': ((value['list'] as Array<any>).map(IoSakurasouControllerVoImagePageVOToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'total': value['total'],
    };
}

