/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IoSakurasouModelStrategyStrategyType } from './IoSakurasouModelStrategyStrategyType';
import {
    IoSakurasouModelStrategyStrategyTypeFromJSON,
    IoSakurasouModelStrategyStrategyTypeFromJSONTyped,
    IoSakurasouModelStrategyStrategyTypeToJSON,
} from './IoSakurasouModelStrategyStrategyType';

/**
 * 
 * @export
 * @interface IoSakurasouModelStrategyLocalStrategy
 */
export interface IoSakurasouModelStrategyLocalStrategy {
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouModelStrategyLocalStrategy
     */
    thumbnailFolder: string;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouModelStrategyLocalStrategy
     */
    uploadFolder: string;
    /**
     * 
     * @type {IoSakurasouModelStrategyStrategyType}
     * @memberof IoSakurasouModelStrategyLocalStrategy
     */
    strategyType: IoSakurasouModelStrategyStrategyType;
}



/**
 * Check if a given object implements the IoSakurasouModelStrategyLocalStrategy interface.
 */
export function instanceOfIoSakurasouModelStrategyLocalStrategy(value: object): value is IoSakurasouModelStrategyLocalStrategy {
    if (!('thumbnailFolder' in value) || value['thumbnailFolder'] === undefined) return false;
    if (!('uploadFolder' in value) || value['uploadFolder'] === undefined) return false;
    if (!('strategyType' in value) || value['strategyType'] === undefined) return false;
    return true;
}

export function IoSakurasouModelStrategyLocalStrategyFromJSON(json: any): IoSakurasouModelStrategyLocalStrategy {
    return IoSakurasouModelStrategyLocalStrategyFromJSONTyped(json, false);
}

export function IoSakurasouModelStrategyLocalStrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouModelStrategyLocalStrategy {
    if (json == null) {
        return json;
    }
    return {
        
        'thumbnailFolder': json['thumbnailFolder'],
        'uploadFolder': json['uploadFolder'],
        'strategyType': IoSakurasouModelStrategyStrategyTypeFromJSON(json['strategyType']),
    };
}

export function IoSakurasouModelStrategyLocalStrategyToJSON(value?: IoSakurasouModelStrategyLocalStrategy | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'thumbnailFolder': value['thumbnailFolder'],
        'uploadFolder': value['uploadFolder'],
        'strategyType': IoSakurasouModelStrategyStrategyTypeToJSON(value['strategyType']),
    };
}

