/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IoSakurasouControllerVoCommonResponseKotlinUnit
 */
export interface IoSakurasouControllerVoCommonResponseKotlinUnit {
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoCommonResponseKotlinUnit
     */
    code: number;
    /**
     * 
     * @type {any}
     * @memberof IoSakurasouControllerVoCommonResponseKotlinUnit
     */
    data?: any | null;
    /**
     * 
     * @type {boolean}
     * @memberof IoSakurasouControllerVoCommonResponseKotlinUnit
     */
    isSuccessful: boolean;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerVoCommonResponseKotlinUnit
     */
    message: string;
}

/**
 * Check if a given object implements the IoSakurasouControllerVoCommonResponseKotlinUnit interface.
 */
export function instanceOfIoSakurasouControllerVoCommonResponseKotlinUnit(value: object): value is IoSakurasouControllerVoCommonResponseKotlinUnit {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('isSuccessful' in value) || value['isSuccessful'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function IoSakurasouControllerVoCommonResponseKotlinUnitFromJSON(json: any): IoSakurasouControllerVoCommonResponseKotlinUnit {
    return IoSakurasouControllerVoCommonResponseKotlinUnitFromJSONTyped(json, false);
}

export function IoSakurasouControllerVoCommonResponseKotlinUnitFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerVoCommonResponseKotlinUnit {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'data': json['data'] == null ? undefined : json['data'],
        'isSuccessful': json['isSuccessful'],
        'message': json['message'],
    };
}

export function IoSakurasouControllerVoCommonResponseKotlinUnitToJSON(value?: IoSakurasouControllerVoCommonResponseKotlinUnit | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'data': value['data'],
        'isSuccessful': value['isSuccessful'],
        'message': value['message'],
    };
}

