/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IoSakurasouControllerRequestUserLoginRequest
 */
export interface IoSakurasouControllerRequestUserLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerRequestUserLoginRequest
     */
    password: string;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerRequestUserLoginRequest
     */
    username: string;
}

/**
 * Check if a given object implements the IoSakurasouControllerRequestUserLoginRequest interface.
 */
export function instanceOfIoSakurasouControllerRequestUserLoginRequest(value: object): value is IoSakurasouControllerRequestUserLoginRequest {
    if (!('password' in value) || value['password'] === undefined) return false;
    if (!('username' in value) || value['username'] === undefined) return false;
    return true;
}

export function IoSakurasouControllerRequestUserLoginRequestFromJSON(json: any): IoSakurasouControllerRequestUserLoginRequest {
    return IoSakurasouControllerRequestUserLoginRequestFromJSONTyped(json, false);
}

export function IoSakurasouControllerRequestUserLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerRequestUserLoginRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'password': json['password'],
        'username': json['username'],
    };
}

export function IoSakurasouControllerRequestUserLoginRequestToJSON(value?: IoSakurasouControllerRequestUserLoginRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'password': value['password'],
        'username': value['username'],
    };
}

