/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IoSakurasouControllerVoGroupPageVO } from './IoSakurasouControllerVoGroupPageVO';
import {
    IoSakurasouControllerVoGroupPageVOFromJSON,
    IoSakurasouControllerVoGroupPageVOFromJSONTyped,
    IoSakurasouControllerVoGroupPageVOToJSON,
} from './IoSakurasouControllerVoGroupPageVO';

/**
 * 
 * @export
 * @interface IoSakurasouControllerVoPageResultioSakurasouControllerVoGroupPageVO
 */
export interface IoSakurasouControllerVoPageResultioSakurasouControllerVoGroupPageVO {
    /**
     * 
     * @type {Array<IoSakurasouControllerVoGroupPageVO>}
     * @memberof IoSakurasouControllerVoPageResultioSakurasouControllerVoGroupPageVO
     */
    list: Array<IoSakurasouControllerVoGroupPageVO>;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoPageResultioSakurasouControllerVoGroupPageVO
     */
    total: number;
}

/**
 * Check if a given object implements the IoSakurasouControllerVoPageResultioSakurasouControllerVoGroupPageVO interface.
 */
export function instanceOfIoSakurasouControllerVoPageResultioSakurasouControllerVoGroupPageVO(value: object): value is IoSakurasouControllerVoPageResultioSakurasouControllerVoGroupPageVO {
    if (!('list' in value) || value['list'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    return true;
}

export function IoSakurasouControllerVoPageResultioSakurasouControllerVoGroupPageVOFromJSON(json: any): IoSakurasouControllerVoPageResultioSakurasouControllerVoGroupPageVO {
    return IoSakurasouControllerVoPageResultioSakurasouControllerVoGroupPageVOFromJSONTyped(json, false);
}

export function IoSakurasouControllerVoPageResultioSakurasouControllerVoGroupPageVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerVoPageResultioSakurasouControllerVoGroupPageVO {
    if (json == null) {
        return json;
    }
    return {
        
        'list': ((json['list'] as Array<any>).map(IoSakurasouControllerVoGroupPageVOFromJSON)),
        'total': json['total'],
    };
}

export function IoSakurasouControllerVoPageResultioSakurasouControllerVoGroupPageVOToJSON(value?: IoSakurasouControllerVoPageResultioSakurasouControllerVoGroupPageVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'list': ((value['list'] as Array<any>).map(IoSakurasouControllerVoGroupPageVOToJSON)),
        'total': value['total'],
    };
}

