/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IoSakurasouModelEntityPermission
 */
export interface IoSakurasouModelEntityPermission {
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouModelEntityPermission
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouModelEntityPermission
     */
    name: string;
}

/**
 * Check if a given object implements the IoSakurasouModelEntityPermission interface.
 */
export function instanceOfIoSakurasouModelEntityPermission(value: object): value is IoSakurasouModelEntityPermission {
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function IoSakurasouModelEntityPermissionFromJSON(json: any): IoSakurasouModelEntityPermission {
    return IoSakurasouModelEntityPermissionFromJSONTyped(json, false);
}

export function IoSakurasouModelEntityPermissionFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouModelEntityPermission {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
    };
}

export function IoSakurasouModelEntityPermissionToJSON(value?: IoSakurasouModelEntityPermission | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'name': value['name'],
    };
}

