/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IoSakurasouModelGroupGroupStrategyConfig } from './IoSakurasouModelGroupGroupStrategyConfig';
import {
    IoSakurasouModelGroupGroupStrategyConfigFromJSON,
    IoSakurasouModelGroupGroupStrategyConfigFromJSONTyped,
    IoSakurasouModelGroupGroupStrategyConfigToJSON,
} from './IoSakurasouModelGroupGroupStrategyConfig';

/**
 * 
 * @export
 * @interface IoSakurasouModelGroupGroupConfig
 */
export interface IoSakurasouModelGroupGroupConfig {
    /**
     * 
     * @type {IoSakurasouModelGroupGroupStrategyConfig}
     * @memberof IoSakurasouModelGroupGroupConfig
     */
    groupStrategyConfig: IoSakurasouModelGroupGroupStrategyConfig;
}

/**
 * Check if a given object implements the IoSakurasouModelGroupGroupConfig interface.
 */
export function instanceOfIoSakurasouModelGroupGroupConfig(value: object): value is IoSakurasouModelGroupGroupConfig {
    if (!('groupStrategyConfig' in value) || value['groupStrategyConfig'] === undefined) return false;
    return true;
}

export function IoSakurasouModelGroupGroupConfigFromJSON(json: any): IoSakurasouModelGroupGroupConfig {
    return IoSakurasouModelGroupGroupConfigFromJSONTyped(json, false);
}

export function IoSakurasouModelGroupGroupConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouModelGroupGroupConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'groupStrategyConfig': IoSakurasouModelGroupGroupStrategyConfigFromJSON(json['groupStrategyConfig']),
    };
}

export function IoSakurasouModelGroupGroupConfigToJSON(value?: IoSakurasouModelGroupGroupConfig | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'groupStrategyConfig': IoSakurasouModelGroupGroupStrategyConfigToJSON(value['groupStrategyConfig']),
    };
}

