/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IoSakurasouModelSettingStrategySetting
 */
export interface IoSakurasouModelSettingStrategySetting {
    /**
     * 
     * @type {Array<string>}
     * @memberof IoSakurasouModelSettingStrategySetting
     */
    allowedImageTypes: Array<string>;
}

/**
 * Check if a given object implements the IoSakurasouModelSettingStrategySetting interface.
 */
export function instanceOfIoSakurasouModelSettingStrategySetting(value: object): value is IoSakurasouModelSettingStrategySetting {
    if (!('allowedImageTypes' in value) || value['allowedImageTypes'] === undefined) return false;
    return true;
}

export function IoSakurasouModelSettingStrategySettingFromJSON(json: any): IoSakurasouModelSettingStrategySetting {
    return IoSakurasouModelSettingStrategySettingFromJSONTyped(json, false);
}

export function IoSakurasouModelSettingStrategySettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouModelSettingStrategySetting {
    if (json == null) {
        return json;
    }
    return {
        
        'allowedImageTypes': json['allowedImageTypes'],
    };
}

export function IoSakurasouModelSettingStrategySettingToJSON(value?: IoSakurasouModelSettingStrategySetting | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'allowedImageTypes': value['allowedImageTypes'],
    };
}

