/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IoSakurasouControllerRequestAlbumPatchRequest
 */
export interface IoSakurasouControllerRequestAlbumPatchRequest {
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerRequestAlbumPatchRequest
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerRequestAlbumPatchRequest
     */
    name?: string;
}

/**
 * Check if a given object implements the IoSakurasouControllerRequestAlbumPatchRequest interface.
 */
export function instanceOfIoSakurasouControllerRequestAlbumPatchRequest(value: object): value is IoSakurasouControllerRequestAlbumPatchRequest {
    return true;
}

export function IoSakurasouControllerRequestAlbumPatchRequestFromJSON(json: any): IoSakurasouControllerRequestAlbumPatchRequest {
    return IoSakurasouControllerRequestAlbumPatchRequestFromJSONTyped(json, false);
}

export function IoSakurasouControllerRequestAlbumPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerRequestAlbumPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function IoSakurasouControllerRequestAlbumPatchRequestToJSON(value?: IoSakurasouControllerRequestAlbumPatchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'name': value['name'],
    };
}

