/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IoSakurasouModelGroupGroupConfig } from './IoSakurasouModelGroupGroupConfig';
import {
    IoSakurasouModelGroupGroupConfigFromJSON,
    IoSakurasouModelGroupGroupConfigFromJSONTyped,
    IoSakurasouModelGroupGroupConfigToJSON,
} from './IoSakurasouModelGroupGroupConfig';

/**
 * 
 * @export
 * @interface IoSakurasouControllerVoGroupVO
 */
export interface IoSakurasouControllerVoGroupVO {
    /**
     * 
     * @type {any}
     * @memberof IoSakurasouControllerVoGroupVO
     */
    description?: any | null;
    /**
     * 
     * @type {IoSakurasouModelGroupGroupConfig}
     * @memberof IoSakurasouControllerVoGroupVO
     */
    groupConfig: IoSakurasouModelGroupGroupConfig;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoGroupVO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerVoGroupVO
     */
    name: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof IoSakurasouControllerVoGroupVO
     */
    roles: Array<string>;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoGroupVO
     */
    strategyId: number;
}

/**
 * Check if a given object implements the IoSakurasouControllerVoGroupVO interface.
 */
export function instanceOfIoSakurasouControllerVoGroupVO(value: object): value is IoSakurasouControllerVoGroupVO {
    if (!('groupConfig' in value) || value['groupConfig'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('roles' in value) || value['roles'] === undefined) return false;
    if (!('strategyId' in value) || value['strategyId'] === undefined) return false;
    return true;
}

export function IoSakurasouControllerVoGroupVOFromJSON(json: any): IoSakurasouControllerVoGroupVO {
    return IoSakurasouControllerVoGroupVOFromJSONTyped(json, false);
}

export function IoSakurasouControllerVoGroupVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerVoGroupVO {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'groupConfig': IoSakurasouModelGroupGroupConfigFromJSON(json['groupConfig']),
        'id': json['id'],
        'name': json['name'],
        'roles': json['roles'],
        'strategyId': json['strategyId'],
    };
}

export function IoSakurasouControllerVoGroupVOToJSON(value?: IoSakurasouControllerVoGroupVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'groupConfig': IoSakurasouModelGroupGroupConfigToJSON(value['groupConfig']),
        'id': value['id'],
        'name': value['name'],
        'roles': value['roles'],
        'strategyId': value['strategyId'],
    };
}

