/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { KotlinxDatetimeLocalDateTime } from './KotlinxDatetimeLocalDateTime';
import {
    KotlinxDatetimeLocalDateTimeFromJSON,
    KotlinxDatetimeLocalDateTimeFromJSONTyped,
    KotlinxDatetimeLocalDateTimeToJSON,
} from './KotlinxDatetimeLocalDateTime';

/**
 * 
 * @export
 * @interface IoSakurasouControllerVoImagePageVO
 */
export interface IoSakurasouControllerVoImagePageVO {
    /**
     * 
     * @type {KotlinxDatetimeLocalDateTime}
     * @memberof IoSakurasouControllerVoImagePageVO
     */
    createTime: KotlinxDatetimeLocalDateTime;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerVoImagePageVO
     */
    displayName: string;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoImagePageVO
     */
    id: number;
    /**
     * 
     * @type {boolean}
     * @memberof IoSakurasouControllerVoImagePageVO
     */
    isPrivate: boolean;
}

/**
 * Check if a given object implements the IoSakurasouControllerVoImagePageVO interface.
 */
export function instanceOfIoSakurasouControllerVoImagePageVO(value: object): value is IoSakurasouControllerVoImagePageVO {
    if (!('createTime' in value) || value['createTime'] === undefined) return false;
    if (!('displayName' in value) || value['displayName'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('isPrivate' in value) || value['isPrivate'] === undefined) return false;
    return true;
}

export function IoSakurasouControllerVoImagePageVOFromJSON(json: any): IoSakurasouControllerVoImagePageVO {
    return IoSakurasouControllerVoImagePageVOFromJSONTyped(json, false);
}

export function IoSakurasouControllerVoImagePageVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerVoImagePageVO {
    if (json == null) {
        return json;
    }
    return {
        
        'createTime': KotlinxDatetimeLocalDateTimeFromJSON(json['createTime']),
        'displayName': json['displayName'],
        'id': json['id'],
        'isPrivate': json['isPrivate'],
    };
}

export function IoSakurasouControllerVoImagePageVOToJSON(value?: IoSakurasouControllerVoImagePageVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'createTime': KotlinxDatetimeLocalDateTimeToJSON(value['createTime']),
        'displayName': value['displayName'],
        'id': value['id'],
        'isPrivate': value['isPrivate'],
    };
}

