/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IoSakurasouModelStrategyStrategyConfig } from './IoSakurasouModelStrategyStrategyConfig';
import {
    IoSakurasouModelStrategyStrategyConfigFromJSON,
    IoSakurasouModelStrategyStrategyConfigFromJSONTyped,
    IoSakurasouModelStrategyStrategyConfigToJSON,
} from './IoSakurasouModelStrategyStrategyConfig';

/**
 * 
 * @export
 * @interface IoSakurasouControllerRequestStrategyPatchRequest
 */
export interface IoSakurasouControllerRequestStrategyPatchRequest {
    /**
     * 
     * @type {IoSakurasouModelStrategyStrategyConfig}
     * @memberof IoSakurasouControllerRequestStrategyPatchRequest
     */
    config?: IoSakurasouModelStrategyStrategyConfig | null;
    /**
     * 
     * @type {any}
     * @memberof IoSakurasouControllerRequestStrategyPatchRequest
     */
    name?: any | null;
}

/**
 * Check if a given object implements the IoSakurasouControllerRequestStrategyPatchRequest interface.
 */
export function instanceOfIoSakurasouControllerRequestStrategyPatchRequest(value: object): value is IoSakurasouControllerRequestStrategyPatchRequest {
    return true;
}

export function IoSakurasouControllerRequestStrategyPatchRequestFromJSON(json: any): IoSakurasouControllerRequestStrategyPatchRequest {
    return IoSakurasouControllerRequestStrategyPatchRequestFromJSONTyped(json, false);
}

export function IoSakurasouControllerRequestStrategyPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerRequestStrategyPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'config': json['config'] == null ? undefined : IoSakurasouModelStrategyStrategyConfigFromJSON(json['config']),
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function IoSakurasouControllerRequestStrategyPatchRequestToJSON(value?: IoSakurasouControllerRequestStrategyPatchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'config': IoSakurasouModelStrategyStrategyConfigToJSON(value['config']),
        'name': value['name'],
    };
}

