/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IoSakurasouModelSettingSystemStatus
 */
export interface IoSakurasouModelSettingSystemStatus {
    /**
     * 
     * @type {boolean}
     * @memberof IoSakurasouModelSettingSystemStatus
     */
    isInit: boolean;
}

/**
 * Check if a given object implements the IoSakurasouModelSettingSystemStatus interface.
 */
export function instanceOfIoSakurasouModelSettingSystemStatus(value: object): value is IoSakurasouModelSettingSystemStatus {
    if (!('isInit' in value) || value['isInit'] === undefined) return false;
    return true;
}

export function IoSakurasouModelSettingSystemStatusFromJSON(json: any): IoSakurasouModelSettingSystemStatus {
    return IoSakurasouModelSettingSystemStatusFromJSONTyped(json, false);
}

export function IoSakurasouModelSettingSystemStatusFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouModelSettingSystemStatus {
    if (json == null) {
        return json;
    }
    return {
        
        'isInit': json['isInit'],
    };
}

export function IoSakurasouModelSettingSystemStatusToJSON(value?: IoSakurasouModelSettingSystemStatus | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'isInit': value['isInit'],
    };
}

