/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IoSakurasouModelStrategyS3Strategy } from './IoSakurasouModelStrategyS3Strategy';
import {
    IoSakurasouModelStrategyS3StrategyFromJSON,
    IoSakurasouModelStrategyS3StrategyFromJSONTyped,
    IoSakurasouModelStrategyS3StrategyToJSON,
} from './IoSakurasouModelStrategyS3Strategy';
import type { IoSakurasouModelStrategyLocalStrategy } from './IoSakurasouModelStrategyLocalStrategy';
import {
    IoSakurasouModelStrategyLocalStrategyFromJSON,
    IoSakurasouModelStrategyLocalStrategyFromJSONTyped,
    IoSakurasouModelStrategyLocalStrategyToJSON,
} from './IoSakurasouModelStrategyLocalStrategy';

/**
 * 
 * @export
 * @interface IoSakurasouModelStrategyStrategyConfig
 */
export interface IoSakurasouModelStrategyStrategyConfig {
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouModelStrategyStrategyConfig
     */
    uploadFolder: string;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouModelStrategyStrategyConfig
     */
    accessKey: string;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouModelStrategyStrategyConfig
     */
    bucketName: string;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouModelStrategyStrategyConfig
     */
    endpoint: string;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouModelStrategyStrategyConfig
     */
    region: string;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouModelStrategyStrategyConfig
     */
    secretKey: string;
}

/**
 * Check if a given object implements the IoSakurasouModelStrategyStrategyConfig interface.
 */
export function instanceOfIoSakurasouModelStrategyStrategyConfig(value: object): value is IoSakurasouModelStrategyStrategyConfig {
    if (!('uploadFolder' in value) || value['uploadFolder'] === undefined) return false;
    if (!('accessKey' in value) || value['accessKey'] === undefined) return false;
    if (!('bucketName' in value) || value['bucketName'] === undefined) return false;
    if (!('endpoint' in value) || value['endpoint'] === undefined) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('secretKey' in value) || value['secretKey'] === undefined) return false;
    return true;
}

export function IoSakurasouModelStrategyStrategyConfigFromJSON(json: any): IoSakurasouModelStrategyStrategyConfig {
    return IoSakurasouModelStrategyStrategyConfigFromJSONTyped(json, false);
}

export function IoSakurasouModelStrategyStrategyConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouModelStrategyStrategyConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'uploadFolder': json['uploadFolder'],
        'accessKey': json['accessKey'],
        'bucketName': json['bucketName'],
        'endpoint': json['endpoint'],
        'region': json['region'],
        'secretKey': json['secretKey'],
    };
}

export function IoSakurasouModelStrategyStrategyConfigToJSON(value?: IoSakurasouModelStrategyStrategyConfig | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'uploadFolder': value['uploadFolder'],
        'accessKey': value['accessKey'],
        'bucketName': value['bucketName'],
        'endpoint': value['endpoint'],
        'region': value['region'],
        'secretKey': value['secretKey'],
    };
}

