/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IoSakurasouControllerVoSettingVO } from './IoSakurasouControllerVoSettingVO';
import {
    IoSakurasouControllerVoSettingVOFromJSON,
    IoSakurasouControllerVoSettingVOFromJSONTyped,
    IoSakurasouControllerVoSettingVOToJSON,
} from './IoSakurasouControllerVoSettingVO';

/**
 * 
 * @export
 * @interface IoSakurasouControllerVoCommonResponsekotlinCollectionsListioSakurasouControllerVoSettingVO
 */
export interface IoSakurasouControllerVoCommonResponsekotlinCollectionsListioSakurasouControllerVoSettingVO {
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoCommonResponsekotlinCollectionsListioSakurasouControllerVoSettingVO
     */
    code: number;
    /**
     * 
     * @type {Array<IoSakurasouControllerVoSettingVO>}
     * @memberof IoSakurasouControllerVoCommonResponsekotlinCollectionsListioSakurasouControllerVoSettingVO
     */
    data?: Array<IoSakurasouControllerVoSettingVO>;
    /**
     * 
     * @type {boolean}
     * @memberof IoSakurasouControllerVoCommonResponsekotlinCollectionsListioSakurasouControllerVoSettingVO
     */
    isSuccessful: boolean;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerVoCommonResponsekotlinCollectionsListioSakurasouControllerVoSettingVO
     */
    message: string;
}

/**
 * Check if a given object implements the IoSakurasouControllerVoCommonResponsekotlinCollectionsListioSakurasouControllerVoSettingVO interface.
 */
export function instanceOfIoSakurasouControllerVoCommonResponsekotlinCollectionsListioSakurasouControllerVoSettingVO(value: object): value is IoSakurasouControllerVoCommonResponsekotlinCollectionsListioSakurasouControllerVoSettingVO {
    if (!('code' in value) || value['code'] === undefined) return false;
    if (!('isSuccessful' in value) || value['isSuccessful'] === undefined) return false;
    if (!('message' in value) || value['message'] === undefined) return false;
    return true;
}

export function IoSakurasouControllerVoCommonResponsekotlinCollectionsListioSakurasouControllerVoSettingVOFromJSON(json: any): IoSakurasouControllerVoCommonResponsekotlinCollectionsListioSakurasouControllerVoSettingVO {
    return IoSakurasouControllerVoCommonResponsekotlinCollectionsListioSakurasouControllerVoSettingVOFromJSONTyped(json, false);
}

export function IoSakurasouControllerVoCommonResponsekotlinCollectionsListioSakurasouControllerVoSettingVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerVoCommonResponsekotlinCollectionsListioSakurasouControllerVoSettingVO {
    if (json == null) {
        return json;
    }
    return {
        
        'code': json['code'],
        'data': json['data'] == null ? undefined : ((json['data'] as Array<any>).map(IoSakurasouControllerVoSettingVOFromJSON)),
        'isSuccessful': json['isSuccessful'],
        'message': json['message'],
    };
}

export function IoSakurasouControllerVoCommonResponsekotlinCollectionsListioSakurasouControllerVoSettingVOToJSON(value?: IoSakurasouControllerVoCommonResponsekotlinCollectionsListioSakurasouControllerVoSettingVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'code': value['code'],
        'data': value['data'] == null ? undefined : ((value['data'] as Array<any>).map(IoSakurasouControllerVoSettingVOToJSON)),
        'isSuccessful': value['isSuccessful'],
        'message': value['message'],
    };
}

