/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IoSakurasouControllerRequestAlbumSelfInsertRequest
 */
export interface IoSakurasouControllerRequestAlbumSelfInsertRequest {
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerRequestAlbumSelfInsertRequest
     */
    description: string;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerRequestAlbumSelfInsertRequest
     */
    name: string;
}

/**
 * Check if a given object implements the IoSakurasouControllerRequestAlbumSelfInsertRequest interface.
 */
export function instanceOfIoSakurasouControllerRequestAlbumSelfInsertRequest(value: object): value is IoSakurasouControllerRequestAlbumSelfInsertRequest {
    if (!('description' in value) || value['description'] === undefined) return false;
    if (!('name' in value) || value['name'] === undefined) return false;
    return true;
}

export function IoSakurasouControllerRequestAlbumSelfInsertRequestFromJSON(json: any): IoSakurasouControllerRequestAlbumSelfInsertRequest {
    return IoSakurasouControllerRequestAlbumSelfInsertRequestFromJSONTyped(json, false);
}

export function IoSakurasouControllerRequestAlbumSelfInsertRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerRequestAlbumSelfInsertRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'],
        'name': json['name'],
    };
}

export function IoSakurasouControllerRequestAlbumSelfInsertRequestToJSON(value?: IoSakurasouControllerRequestAlbumSelfInsertRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'name': value['name'],
    };
}

