/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IoSakurasouControllerRequestSiteSettingPatchRequest
 */
export interface IoSakurasouControllerRequestSiteSettingPatchRequest {
    /**
     * 
     * @type {any}
     * @memberof IoSakurasouControllerRequestSiteSettingPatchRequest
     */
    homePageRandomPicDisplay?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IoSakurasouControllerRequestSiteSettingPatchRequest
     */
    siteDescription?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IoSakurasouControllerRequestSiteSettingPatchRequest
     */
    siteExternalUrl?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IoSakurasouControllerRequestSiteSettingPatchRequest
     */
    siteKeyword?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IoSakurasouControllerRequestSiteSettingPatchRequest
     */
    siteSubtitle?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IoSakurasouControllerRequestSiteSettingPatchRequest
     */
    siteTitle?: any | null;
}

/**
 * Check if a given object implements the IoSakurasouControllerRequestSiteSettingPatchRequest interface.
 */
export function instanceOfIoSakurasouControllerRequestSiteSettingPatchRequest(value: object): value is IoSakurasouControllerRequestSiteSettingPatchRequest {
    return true;
}

export function IoSakurasouControllerRequestSiteSettingPatchRequestFromJSON(json: any): IoSakurasouControllerRequestSiteSettingPatchRequest {
    return IoSakurasouControllerRequestSiteSettingPatchRequestFromJSONTyped(json, false);
}

export function IoSakurasouControllerRequestSiteSettingPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerRequestSiteSettingPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'homePageRandomPicDisplay': json['homePageRandomPicDisplay'] == null ? undefined : json['homePageRandomPicDisplay'],
        'siteDescription': json['siteDescription'] == null ? undefined : json['siteDescription'],
        'siteExternalUrl': json['siteExternalUrl'] == null ? undefined : json['siteExternalUrl'],
        'siteKeyword': json['siteKeyword'] == null ? undefined : json['siteKeyword'],
        'siteSubtitle': json['siteSubtitle'] == null ? undefined : json['siteSubtitle'],
        'siteTitle': json['siteTitle'] == null ? undefined : json['siteTitle'],
    };
}

export function IoSakurasouControllerRequestSiteSettingPatchRequestToJSON(value?: IoSakurasouControllerRequestSiteSettingPatchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'homePageRandomPicDisplay': value['homePageRandomPicDisplay'],
        'siteDescription': value['siteDescription'],
        'siteExternalUrl': value['siteExternalUrl'],
        'siteKeyword': value['siteKeyword'],
        'siteSubtitle': value['siteSubtitle'],
        'siteTitle': value['siteTitle'],
    };
}

