/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IoSakurasouControllerVoImagePageVO
 */
export interface IoSakurasouControllerVoImagePageVO {
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerVoImagePageVO
     */
    externalUrl: string;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoImagePageVO
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouControllerVoImagePageVO
     */
    originName: string;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoImagePageVO
     */
    size: number;
}

/**
 * Check if a given object implements the IoSakurasouControllerVoImagePageVO interface.
 */
export function instanceOfIoSakurasouControllerVoImagePageVO(value: object): value is IoSakurasouControllerVoImagePageVO {
    if (!('externalUrl' in value) || value['externalUrl'] === undefined) return false;
    if (!('id' in value) || value['id'] === undefined) return false;
    if (!('originName' in value) || value['originName'] === undefined) return false;
    if (!('size' in value) || value['size'] === undefined) return false;
    return true;
}

export function IoSakurasouControllerVoImagePageVOFromJSON(json: any): IoSakurasouControllerVoImagePageVO {
    return IoSakurasouControllerVoImagePageVOFromJSONTyped(json, false);
}

export function IoSakurasouControllerVoImagePageVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerVoImagePageVO {
    if (json == null) {
        return json;
    }
    return {
        
        'externalUrl': json['externalUrl'],
        'id': json['id'],
        'originName': json['originName'],
        'size': json['size'],
    };
}

export function IoSakurasouControllerVoImagePageVOToJSON(value?: IoSakurasouControllerVoImagePageVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'externalUrl': value['externalUrl'],
        'id': value['id'],
        'originName': value['originName'],
        'size': value['size'],
    };
}

