/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IoSakurasouControllerVoAlbumPageVO } from './IoSakurasouControllerVoAlbumPageVO';
import {
    IoSakurasouControllerVoAlbumPageVOFromJSON,
    IoSakurasouControllerVoAlbumPageVOFromJSONTyped,
    IoSakurasouControllerVoAlbumPageVOToJSON,
} from './IoSakurasouControllerVoAlbumPageVO';

/**
 * 
 * @export
 * @interface IoSakurasouControllerVoPageResultIoSakurasouControllerVoAlbumPageVO
 */
export interface IoSakurasouControllerVoPageResultIoSakurasouControllerVoAlbumPageVO {
    /**
     * 
     * @type {Array<IoSakurasouControllerVoAlbumPageVO>}
     * @memberof IoSakurasouControllerVoPageResultIoSakurasouControllerVoAlbumPageVO
     */
    data: Array<IoSakurasouControllerVoAlbumPageVO>;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoPageResultIoSakurasouControllerVoAlbumPageVO
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoPageResultIoSakurasouControllerVoAlbumPageVO
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoPageResultIoSakurasouControllerVoAlbumPageVO
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoPageResultIoSakurasouControllerVoAlbumPageVO
     */
    totalPage: number;
}

/**
 * Check if a given object implements the IoSakurasouControllerVoPageResultIoSakurasouControllerVoAlbumPageVO interface.
 */
export function instanceOfIoSakurasouControllerVoPageResultIoSakurasouControllerVoAlbumPageVO(value: object): value is IoSakurasouControllerVoPageResultIoSakurasouControllerVoAlbumPageVO {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    return true;
}

export function IoSakurasouControllerVoPageResultIoSakurasouControllerVoAlbumPageVOFromJSON(json: any): IoSakurasouControllerVoPageResultIoSakurasouControllerVoAlbumPageVO {
    return IoSakurasouControllerVoPageResultIoSakurasouControllerVoAlbumPageVOFromJSONTyped(json, false);
}

export function IoSakurasouControllerVoPageResultIoSakurasouControllerVoAlbumPageVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerVoPageResultIoSakurasouControllerVoAlbumPageVO {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(IoSakurasouControllerVoAlbumPageVOFromJSON)),
        'page': json['page'],
        'pageSize': json['pageSize'],
        'total': json['total'],
        'totalPage': json['totalPage'],
    };
}

export function IoSakurasouControllerVoPageResultIoSakurasouControllerVoAlbumPageVOToJSON(value?: IoSakurasouControllerVoPageResultIoSakurasouControllerVoAlbumPageVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(IoSakurasouControllerVoAlbumPageVOToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'total': value['total'],
        'totalPage': value['totalPage'],
    };
}

