/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IoSakurasouControllerRequestAlbumManagePatchRequest
 */
export interface IoSakurasouControllerRequestAlbumManagePatchRequest {
    /**
     * 
     * @type {any}
     * @memberof IoSakurasouControllerRequestAlbumManagePatchRequest
     */
    description?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IoSakurasouControllerRequestAlbumManagePatchRequest
     */
    name?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IoSakurasouControllerRequestAlbumManagePatchRequest
     */
    userId?: any | null;
}

/**
 * Check if a given object implements the IoSakurasouControllerRequestAlbumManagePatchRequest interface.
 */
export function instanceOfIoSakurasouControllerRequestAlbumManagePatchRequest(value: object): value is IoSakurasouControllerRequestAlbumManagePatchRequest {
    return true;
}

export function IoSakurasouControllerRequestAlbumManagePatchRequestFromJSON(json: any): IoSakurasouControllerRequestAlbumManagePatchRequest {
    return IoSakurasouControllerRequestAlbumManagePatchRequestFromJSONTyped(json, false);
}

export function IoSakurasouControllerRequestAlbumManagePatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerRequestAlbumManagePatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'] == null ? undefined : json['name'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function IoSakurasouControllerRequestAlbumManagePatchRequestToJSON(value?: IoSakurasouControllerRequestAlbumManagePatchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'description': value['description'],
        'name': value['name'],
        'userId': value['userId'],
    };
}

