/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { IoSakurasouControllerVoImagePageVO } from './IoSakurasouControllerVoImagePageVO';
import {
    IoSakurasouControllerVoImagePageVOFromJSON,
    IoSakurasouControllerVoImagePageVOFromJSONTyped,
    IoSakurasouControllerVoImagePageVOToJSON,
} from './IoSakurasouControllerVoImagePageVO';

/**
 * 
 * @export
 * @interface IoSakurasouControllerVoPageResultIoSakurasouControllerVoImagePageVO
 */
export interface IoSakurasouControllerVoPageResultIoSakurasouControllerVoImagePageVO {
    /**
     * 
     * @type {Array<IoSakurasouControllerVoImagePageVO>}
     * @memberof IoSakurasouControllerVoPageResultIoSakurasouControllerVoImagePageVO
     */
    data: Array<IoSakurasouControllerVoImagePageVO>;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoPageResultIoSakurasouControllerVoImagePageVO
     */
    page: number;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoPageResultIoSakurasouControllerVoImagePageVO
     */
    pageSize: number;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoPageResultIoSakurasouControllerVoImagePageVO
     */
    total: number;
    /**
     * 
     * @type {number}
     * @memberof IoSakurasouControllerVoPageResultIoSakurasouControllerVoImagePageVO
     */
    totalPage: number;
}

/**
 * Check if a given object implements the IoSakurasouControllerVoPageResultIoSakurasouControllerVoImagePageVO interface.
 */
export function instanceOfIoSakurasouControllerVoPageResultIoSakurasouControllerVoImagePageVO(value: object): value is IoSakurasouControllerVoPageResultIoSakurasouControllerVoImagePageVO {
    if (!('data' in value) || value['data'] === undefined) return false;
    if (!('page' in value) || value['page'] === undefined) return false;
    if (!('pageSize' in value) || value['pageSize'] === undefined) return false;
    if (!('total' in value) || value['total'] === undefined) return false;
    if (!('totalPage' in value) || value['totalPage'] === undefined) return false;
    return true;
}

export function IoSakurasouControllerVoPageResultIoSakurasouControllerVoImagePageVOFromJSON(json: any): IoSakurasouControllerVoPageResultIoSakurasouControllerVoImagePageVO {
    return IoSakurasouControllerVoPageResultIoSakurasouControllerVoImagePageVOFromJSONTyped(json, false);
}

export function IoSakurasouControllerVoPageResultIoSakurasouControllerVoImagePageVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerVoPageResultIoSakurasouControllerVoImagePageVO {
    if (json == null) {
        return json;
    }
    return {
        
        'data': ((json['data'] as Array<any>).map(IoSakurasouControllerVoImagePageVOFromJSON)),
        'page': json['page'],
        'pageSize': json['pageSize'],
        'total': json['total'],
        'totalPage': json['totalPage'],
    };
}

export function IoSakurasouControllerVoPageResultIoSakurasouControllerVoImagePageVOToJSON(value?: IoSakurasouControllerVoPageResultIoSakurasouControllerVoImagePageVO | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'data': ((value['data'] as Array<any>).map(IoSakurasouControllerVoImagePageVOToJSON)),
        'page': value['page'],
        'pageSize': value['pageSize'],
        'total': value['total'],
        'totalPage': value['totalPage'],
    };
}

