/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IoSakurasouControllerRequestImageManagePatchRequest
 */
export interface IoSakurasouControllerRequestImageManagePatchRequest {
    /**
     * 
     * @type {any}
     * @memberof IoSakurasouControllerRequestImageManagePatchRequest
     */
    albumId?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IoSakurasouControllerRequestImageManagePatchRequest
     */
    description?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IoSakurasouControllerRequestImageManagePatchRequest
     */
    displayName?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IoSakurasouControllerRequestImageManagePatchRequest
     */
    isPrivate?: any | null;
    /**
     * 
     * @type {any}
     * @memberof IoSakurasouControllerRequestImageManagePatchRequest
     */
    userId?: any | null;
}

/**
 * Check if a given object implements the IoSakurasouControllerRequestImageManagePatchRequest interface.
 */
export function instanceOfIoSakurasouControllerRequestImageManagePatchRequest(value: object): value is IoSakurasouControllerRequestImageManagePatchRequest {
    return true;
}

export function IoSakurasouControllerRequestImageManagePatchRequestFromJSON(json: any): IoSakurasouControllerRequestImageManagePatchRequest {
    return IoSakurasouControllerRequestImageManagePatchRequestFromJSONTyped(json, false);
}

export function IoSakurasouControllerRequestImageManagePatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouControllerRequestImageManagePatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'albumId': json['albumId'] == null ? undefined : json['albumId'],
        'description': json['description'] == null ? undefined : json['description'],
        'displayName': json['displayName'] == null ? undefined : json['displayName'],
        'isPrivate': json['isPrivate'] == null ? undefined : json['isPrivate'],
        'userId': json['userId'] == null ? undefined : json['userId'],
    };
}

export function IoSakurasouControllerRequestImageManagePatchRequestToJSON(value?: IoSakurasouControllerRequestImageManagePatchRequest | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'albumId': value['albumId'],
        'description': value['description'],
        'displayName': value['displayName'],
        'isPrivate': value['isPrivate'],
        'userId': value['userId'],
    };
}

