/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface IoSakurasouModelStrategyS3Strategy
 */
export interface IoSakurasouModelStrategyS3Strategy {
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouModelStrategyS3Strategy
     */
    accessKey: string;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouModelStrategyS3Strategy
     */
    bucketName: string;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouModelStrategyS3Strategy
     */
    endpoint: string;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouModelStrategyS3Strategy
     */
    region: string;
    /**
     * 
     * @type {string}
     * @memberof IoSakurasouModelStrategyS3Strategy
     */
    secretKey: string;
}

/**
 * Check if a given object implements the IoSakurasouModelStrategyS3Strategy interface.
 */
export function instanceOfIoSakurasouModelStrategyS3Strategy(value: object): value is IoSakurasouModelStrategyS3Strategy {
    if (!('accessKey' in value) || value['accessKey'] === undefined) return false;
    if (!('bucketName' in value) || value['bucketName'] === undefined) return false;
    if (!('endpoint' in value) || value['endpoint'] === undefined) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('secretKey' in value) || value['secretKey'] === undefined) return false;
    return true;
}

export function IoSakurasouModelStrategyS3StrategyFromJSON(json: any): IoSakurasouModelStrategyS3Strategy {
    return IoSakurasouModelStrategyS3StrategyFromJSONTyped(json, false);
}

export function IoSakurasouModelStrategyS3StrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): IoSakurasouModelStrategyS3Strategy {
    if (json == null) {
        return json;
    }
    return {
        
        'accessKey': json['accessKey'],
        'bucketName': json['bucketName'],
        'endpoint': json['endpoint'],
        'region': json['region'],
        'secretKey': json['secretKey'],
    };
}

export function IoSakurasouModelStrategyS3StrategyToJSON(value?: IoSakurasouModelStrategyS3Strategy | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'accessKey': value['accessKey'],
        'bucketName': value['bucketName'],
        'endpoint': value['endpoint'],
        'region': value['region'],
        'secretKey': value['secretKey'],
    };
}

