/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface KotlinxSerializationJsonJsonLiteral
 */
export interface KotlinxSerializationJsonJsonLiteral {
    /**
     * 
     * @type {string}
     * @memberof KotlinxSerializationJsonJsonLiteral
     */
    content: string;
    /**
     * 
     * @type {boolean}
     * @memberof KotlinxSerializationJsonJsonLiteral
     */
    isString: boolean;
}

/**
 * Check if a given object implements the KotlinxSerializationJsonJsonLiteral interface.
 */
export function instanceOfKotlinxSerializationJsonJsonLiteral(value: object): value is KotlinxSerializationJsonJsonLiteral {
    if (!('content' in value) || value['content'] === undefined) return false;
    if (!('isString' in value) || value['isString'] === undefined) return false;
    return true;
}

export function KotlinxSerializationJsonJsonLiteralFromJSON(json: any): KotlinxSerializationJsonJsonLiteral {
    return KotlinxSerializationJsonJsonLiteralFromJSONTyped(json, false);
}

export function KotlinxSerializationJsonJsonLiteralFromJSONTyped(json: any, ignoreDiscriminator: boolean): KotlinxSerializationJsonJsonLiteral {
    if (json == null) {
        return json;
    }
    return {
        
        'content': json['content'],
        'isString': json['isString'],
    };
}

export function KotlinxSerializationJsonJsonLiteralToJSON(value?: KotlinxSerializationJsonJsonLiteral | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'content': value['content'],
        'isString': value['isString'],
    };
}

