/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { KotlinxDatetimeLocalDateTime } from './kotlinx-datetime-local-date-time';

/**
 * 
 * @export
 * @interface PersonalAccessTokenInsertRequest
 */
export interface PersonalAccessTokenInsertRequest {
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessTokenInsertRequest
     */
    'description'?: string | null;
    /**
     * 
     * @type {KotlinxDatetimeLocalDateTime}
     * @memberof PersonalAccessTokenInsertRequest
     */
    'expireTime': KotlinxDatetimeLocalDateTime;
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessTokenInsertRequest
     */
    'name': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof PersonalAccessTokenInsertRequest
     */
    'permissions': Array<string>;
}

