/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface PersonalAccessTokenPageVO
 */
export interface PersonalAccessTokenPageVO {
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessTokenPageVO
     */
    'createTime': string;
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessTokenPageVO
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessTokenPageVO
     */
    'expireTime': string;
    /**
     * 
     * @type {number}
     * @memberof PersonalAccessTokenPageVO
     */
    'id': number;
    /**
     * 
     * @type {boolean}
     * @memberof PersonalAccessTokenPageVO
     */
    'isExpired': boolean;
    /**
     * 
     * @type {string}
     * @memberof PersonalAccessTokenPageVO
     */
    'name': string;
}

