/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface RoleInsertRequest
 */
export interface RoleInsertRequest {
    /**
     * 
     * @type {string}
     * @memberof RoleInsertRequest
     */
    'description'?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RoleInsertRequest
     */
    'displayName': string;
    /**
     * 
     * @type {string}
     * @memberof RoleInsertRequest
     */
    'name': string;
    /**
     * 
     * @type {Array<string>}
     * @memberof RoleInsertRequest
     */
    'permissions': Array<string>;
}

