/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { PermissionVO } from './PermissionVO';
import {
    PermissionVOFromJSON,
    PermissionVOFromJSONTyped,
    PermissionVOToJSON,
    PermissionVOToJSONTyped,
} from './PermissionVO';

/**
 * 
 * @export
 * @interface RoleVO
 */
export interface RoleVO {
    /**
     * 
     * @type {string}
     * @memberof RoleVO
     */
    description?: string | null;
    /**
     * 
     * @type {string}
     * @memberof RoleVO
     */
    name: string;
    /**
     * 
     * @type {Array<PermissionVO>}
     * @memberof RoleVO
     */
    permissions: Array<PermissionVO>;
}

/**
 * Check if a given object implements the RoleVO interface.
 */
export function instanceOfRoleVO(value: object): value is RoleVO {
    if (!('name' in value) || value['name'] === undefined) return false;
    if (!('permissions' in value) || value['permissions'] === undefined) return false;
    return true;
}

export function RoleVOFromJSON(json: any): RoleVO {
    return RoleVOFromJSONTyped(json, false);
}

export function RoleVOFromJSONTyped(json: any, ignoreDiscriminator: boolean): RoleVO {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'name': json['name'],
        'permissions': ((json['permissions'] as Array<any>).map(PermissionVOFromJSON)),
    };
}

  export function RoleVOToJSON(json: any): RoleVO {
      return RoleVOToJSONTyped(json, false);
  }

  export function RoleVOToJSONTyped(value?: RoleVO | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'name': value['name'],
        'permissions': ((value['permissions'] as Array<any>).map(PermissionVOToJSON)),
    };
}

