/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { StrategyTypeEnum } from './StrategyTypeEnum';
import {
    StrategyTypeEnumFromJSON,
    StrategyTypeEnumFromJSONTyped,
    StrategyTypeEnumToJSON,
    StrategyTypeEnumToJSONTyped,
} from './StrategyTypeEnum';

/**
 * 
 * @export
 * @interface S3Strategy
 */
export interface S3Strategy {
    /**
     * 
     * @type {string}
     * @memberof S3Strategy
     */
    accessKey: string;
    /**
     * 
     * @type {string}
     * @memberof S3Strategy
     */
    bucketName: string;
    /**
     * 
     * @type {string}
     * @memberof S3Strategy
     */
    endpoint: string;
    /**
     * 
     * @type {string}
     * @memberof S3Strategy
     */
    publicUrl: string;
    /**
     * 
     * @type {string}
     * @memberof S3Strategy
     */
    region: string;
    /**
     * 
     * @type {string}
     * @memberof S3Strategy
     */
    secretKey: string;
    /**
     * 
     * @type {string}
     * @memberof S3Strategy
     */
    thumbnailFolder: string;
    /**
     * 
     * @type {string}
     * @memberof S3Strategy
     */
    uploadFolder: string;
    /**
     * 
     * @type {StrategyTypeEnum}
     * @memberof S3Strategy
     */
    strategyType: StrategyTypeEnum;
}



/**
 * Check if a given object implements the S3Strategy interface.
 */
export function instanceOfS3Strategy(value: object): value is S3Strategy {
    if (!('accessKey' in value) || value['accessKey'] === undefined) return false;
    if (!('bucketName' in value) || value['bucketName'] === undefined) return false;
    if (!('endpoint' in value) || value['endpoint'] === undefined) return false;
    if (!('publicUrl' in value) || value['publicUrl'] === undefined) return false;
    if (!('region' in value) || value['region'] === undefined) return false;
    if (!('secretKey' in value) || value['secretKey'] === undefined) return false;
    if (!('thumbnailFolder' in value) || value['thumbnailFolder'] === undefined) return false;
    if (!('uploadFolder' in value) || value['uploadFolder'] === undefined) return false;
    if (!('strategyType' in value) || value['strategyType'] === undefined) return false;
    return true;
}

export function S3StrategyFromJSON(json: any): S3Strategy {
    return S3StrategyFromJSONTyped(json, false);
}

export function S3StrategyFromJSONTyped(json: any, ignoreDiscriminator: boolean): S3Strategy {
    if (json == null) {
        return json;
    }
    return {
        
        'accessKey': json['accessKey'],
        'bucketName': json['bucketName'],
        'endpoint': json['endpoint'],
        'publicUrl': json['publicUrl'],
        'region': json['region'],
        'secretKey': json['secretKey'],
        'thumbnailFolder': json['thumbnailFolder'],
        'uploadFolder': json['uploadFolder'],
        'strategyType': StrategyTypeEnumFromJSON(json['strategyType']),
    };
}

  export function S3StrategyToJSON(json: any): S3Strategy {
      return S3StrategyToJSONTyped(json, false);
  }

  export function S3StrategyToJSONTyped(value?: S3Strategy | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'accessKey': value['accessKey'],
        'bucketName': value['bucketName'],
        'endpoint': value['endpoint'],
        'publicUrl': value['publicUrl'],
        'region': value['region'],
        'secretKey': value['secretKey'],
        'thumbnailFolder': value['thumbnailFolder'],
        'uploadFolder': value['uploadFolder'],
        'strategyType': StrategyTypeEnumToJSON(value['strategyType']),
    };
}

