/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { SystemStatus } from './SystemStatus';
import {
    SystemStatusFromJSON,
    SystemStatusFromJSONTyped,
    SystemStatusToJSON,
    SystemStatusToJSONTyped,
} from './SystemStatus';
import type { SystemSetting } from './SystemSetting';
import {
    SystemSettingFromJSON,
    SystemSettingFromJSONTyped,
    SystemSettingToJSON,
    SystemSettingToJSONTyped,
} from './SystemSetting';
import type { SiteSetting } from './SiteSetting';
import {
    SiteSettingFromJSON,
    SiteSettingFromJSONTyped,
    SiteSettingToJSON,
    SiteSettingToJSONTyped,
} from './SiteSetting';

/**
 * 
 * @export
 * @interface SettingConfigSealed
 */
export interface SettingConfigSealed {
    /**
     * 
     * @type {boolean}
     * @memberof SettingConfigSealed
     */
    homePageRandomPicDisplay: boolean;
    /**
     * 
     * @type {string}
     * @memberof SettingConfigSealed
     */
    siteDescription: string;
    /**
     * 
     * @type {string}
     * @memberof SettingConfigSealed
     */
    siteExternalUrl: string;
    /**
     * 
     * @type {string}
     * @memberof SettingConfigSealed
     */
    siteKeyword: string;
    /**
     * 
     * @type {string}
     * @memberof SettingConfigSealed
     */
    siteSubtitle: string;
    /**
     * 
     * @type {string}
     * @memberof SettingConfigSealed
     */
    siteTitle: string;
    /**
     * 
     * @type {boolean}
     * @memberof SettingConfigSealed
     */
    allowRandomFetch: boolean;
    /**
     * 
     * @type {boolean}
     * @memberof SettingConfigSealed
     */
    allowSignup: boolean;
    /**
     * 
     * @type {number}
     * @memberof SettingConfigSealed
     */
    defaultGroupId: number;
    /**
     * 
     * @type {boolean}
     * @memberof SettingConfigSealed
     */
    isInit: boolean;
}

/**
 * Check if a given object implements the SettingConfigSealed interface.
 */
export function instanceOfSettingConfigSealed(value: object): value is SettingConfigSealed {
    if (!('homePageRandomPicDisplay' in value) || value['homePageRandomPicDisplay'] === undefined) return false;
    if (!('siteDescription' in value) || value['siteDescription'] === undefined) return false;
    if (!('siteExternalUrl' in value) || value['siteExternalUrl'] === undefined) return false;
    if (!('siteKeyword' in value) || value['siteKeyword'] === undefined) return false;
    if (!('siteSubtitle' in value) || value['siteSubtitle'] === undefined) return false;
    if (!('siteTitle' in value) || value['siteTitle'] === undefined) return false;
    if (!('allowRandomFetch' in value) || value['allowRandomFetch'] === undefined) return false;
    if (!('allowSignup' in value) || value['allowSignup'] === undefined) return false;
    if (!('defaultGroupId' in value) || value['defaultGroupId'] === undefined) return false;
    if (!('isInit' in value) || value['isInit'] === undefined) return false;
    return true;
}

export function SettingConfigSealedFromJSON(json: any): SettingConfigSealed {
    return SettingConfigSealedFromJSONTyped(json, false);
}

export function SettingConfigSealedFromJSONTyped(json: any, ignoreDiscriminator: boolean): SettingConfigSealed {
    if (json == null) {
        return json;
    }
    return {
        
        'homePageRandomPicDisplay': json['homePageRandomPicDisplay'],
        'siteDescription': json['siteDescription'],
        'siteExternalUrl': json['siteExternalUrl'],
        'siteKeyword': json['siteKeyword'],
        'siteSubtitle': json['siteSubtitle'],
        'siteTitle': json['siteTitle'],
        'allowRandomFetch': json['allowRandomFetch'],
        'allowSignup': json['allowSignup'],
        'defaultGroupId': json['defaultGroupId'],
        'isInit': json['isInit'],
    };
}

  export function SettingConfigSealedToJSON(json: any): SettingConfigSealed {
      return SettingConfigSealedToJSONTyped(json, false);
  }

  export function SettingConfigSealedToJSONTyped(value?: SettingConfigSealed | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'homePageRandomPicDisplay': value['homePageRandomPicDisplay'],
        'siteDescription': value['siteDescription'],
        'siteExternalUrl': value['siteExternalUrl'],
        'siteKeyword': value['siteKeyword'],
        'siteSubtitle': value['siteSubtitle'],
        'siteTitle': value['siteTitle'],
        'allowRandomFetch': value['allowRandomFetch'],
        'allowSignup': value['allowSignup'],
        'defaultGroupId': value['defaultGroupId'],
        'isInit': value['isInit'],
    };
}

