/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { SettingConfigSealed } from './setting-config-sealed';

/**
 * 
 * @export
 * @interface SettingVO
 */
export interface SettingVO {
    /**
     * 
     * @type {SettingConfigSealed}
     * @memberof SettingVO
     */
    'config': SettingConfigSealed;
    /**
     * 
     * @type {string}
     * @memberof SettingVO
     */
    'name': string;
}

