/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface SiteInitRequest
 */
export interface SiteInitRequest {
    /**
     * 
     * @type {string}
     * @memberof SiteInitRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof SiteInitRequest
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof SiteInitRequest
     */
    'siteDescription': string;
    /**
     * 
     * @type {string}
     * @memberof SiteInitRequest
     */
    'siteExternalUrl': string;
    /**
     * 
     * @type {string}
     * @memberof SiteInitRequest
     */
    'siteSubtitle': string;
    /**
     * 
     * @type {string}
     * @memberof SiteInitRequest
     */
    'siteTitle': string;
    /**
     * 
     * @type {string}
     * @memberof SiteInitRequest
     */
    'username': string;
}

