/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SiteSetting
 */
export interface SiteSetting {
    /**
     * 
     * @type {boolean}
     * @memberof SiteSetting
     */
    homePageRandomPicDisplay: boolean;
    /**
     * 
     * @type {string}
     * @memberof SiteSetting
     */
    siteDescription: string;
    /**
     * 
     * @type {string}
     * @memberof SiteSetting
     */
    siteExternalUrl: string;
    /**
     * 
     * @type {string}
     * @memberof SiteSetting
     */
    siteKeyword: string;
    /**
     * 
     * @type {string}
     * @memberof SiteSetting
     */
    siteSubtitle: string;
    /**
     * 
     * @type {string}
     * @memberof SiteSetting
     */
    siteTitle: string;
}

/**
 * Check if a given object implements the SiteSetting interface.
 */
export function instanceOfSiteSetting(value: object): value is SiteSetting {
    if (!('homePageRandomPicDisplay' in value) || value['homePageRandomPicDisplay'] === undefined) return false;
    if (!('siteDescription' in value) || value['siteDescription'] === undefined) return false;
    if (!('siteExternalUrl' in value) || value['siteExternalUrl'] === undefined) return false;
    if (!('siteKeyword' in value) || value['siteKeyword'] === undefined) return false;
    if (!('siteSubtitle' in value) || value['siteSubtitle'] === undefined) return false;
    if (!('siteTitle' in value) || value['siteTitle'] === undefined) return false;
    return true;
}

export function SiteSettingFromJSON(json: any): SiteSetting {
    return SiteSettingFromJSONTyped(json, false);
}

export function SiteSettingFromJSONTyped(json: any, ignoreDiscriminator: boolean): SiteSetting {
    if (json == null) {
        return json;
    }
    return {
        
        'homePageRandomPicDisplay': json['homePageRandomPicDisplay'],
        'siteDescription': json['siteDescription'],
        'siteExternalUrl': json['siteExternalUrl'],
        'siteKeyword': json['siteKeyword'],
        'siteSubtitle': json['siteSubtitle'],
        'siteTitle': json['siteTitle'],
    };
}

  export function SiteSettingToJSON(json: any): SiteSetting {
      return SiteSettingToJSONTyped(json, false);
  }

  export function SiteSettingToJSONTyped(value?: SiteSetting | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'homePageRandomPicDisplay': value['homePageRandomPicDisplay'],
        'siteDescription': value['siteDescription'],
        'siteExternalUrl': value['siteExternalUrl'],
        'siteKeyword': value['siteKeyword'],
        'siteSubtitle': value['siteSubtitle'],
        'siteTitle': value['siteTitle'],
    };
}

