/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StrategySettingPatchRequest
 */
export interface StrategySettingPatchRequest {
    /**
     * 
     * @type {Array<string>}
     * @memberof StrategySettingPatchRequest
     */
    allowedImageTypes: Array<string>;
}

/**
 * Check if a given object implements the StrategySettingPatchRequest interface.
 */
export function instanceOfStrategySettingPatchRequest(value: object): value is StrategySettingPatchRequest {
    if (!('allowedImageTypes' in value) || value['allowedImageTypes'] === undefined) return false;
    return true;
}

export function StrategySettingPatchRequestFromJSON(json: any): StrategySettingPatchRequest {
    return StrategySettingPatchRequestFromJSONTyped(json, false);
}

export function StrategySettingPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrategySettingPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'allowedImageTypes': json['allowedImageTypes'],
    };
}

  export function StrategySettingPatchRequestToJSON(json: any): StrategySettingPatchRequest {
      return StrategySettingPatchRequestToJSONTyped(json, false);
  }

  export function StrategySettingPatchRequestToJSONTyped(value?: StrategySettingPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'allowedImageTypes': value['allowedImageTypes'],
    };
}

