/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * S3 strategy configuration
 * @export
 * @interface StrategyRequestS3StrategyConfig
 */
export interface StrategyRequestS3StrategyConfig {
    /**
     * 
     * @type {any}
     * @memberof StrategyRequestS3StrategyConfig
     */
    endpoint?: any | null;
    /**
     * 
     * @type {any}
     * @memberof StrategyRequestS3StrategyConfig
     */
    bucketName?: any | null;
    /**
     * 
     * @type {any}
     * @memberof StrategyRequestS3StrategyConfig
     */
    region?: any | null;
    /**
     * 
     * @type {any}
     * @memberof StrategyRequestS3StrategyConfig
     */
    accessKey?: any | null;
    /**
     * 
     * @type {any}
     * @memberof StrategyRequestS3StrategyConfig
     */
    secretKey?: any | null;
    /**
     * 
     * @type {any}
     * @memberof StrategyRequestS3StrategyConfig
     */
    uploadFolder?: any | null;
    /**
     * 
     * @type {any}
     * @memberof StrategyRequestS3StrategyConfig
     */
    thumbnailFolder?: any | null;
    /**
     * 
     * @type {any}
     * @memberof StrategyRequestS3StrategyConfig
     */
    publicUrl?: any | null;
    /**
     * 
     * @type {any}
     * @memberof StrategyRequestS3StrategyConfig
     */
    strategyType?: any | null;
    /**
     * 
     * @type {any}
     * @memberof StrategyRequestS3StrategyConfig
     */
    type?: any | null;
}

/**
 * Check if a given object implements the StrategyRequestS3StrategyConfig interface.
 */
export function instanceOfStrategyRequestS3StrategyConfig(value: object): value is StrategyRequestS3StrategyConfig {
    return true;
}

export function StrategyRequestS3StrategyConfigFromJSON(json: any): StrategyRequestS3StrategyConfig {
    return StrategyRequestS3StrategyConfigFromJSONTyped(json, false);
}

export function StrategyRequestS3StrategyConfigFromJSONTyped(json: any, ignoreDiscriminator: boolean): StrategyRequestS3StrategyConfig {
    if (json == null) {
        return json;
    }
    return {
        
        'endpoint': json['endpoint'] == null ? undefined : json['endpoint'],
        'bucketName': json['bucketName'] == null ? undefined : json['bucketName'],
        'region': json['region'] == null ? undefined : json['region'],
        'accessKey': json['accessKey'] == null ? undefined : json['accessKey'],
        'secretKey': json['secretKey'] == null ? undefined : json['secretKey'],
        'uploadFolder': json['uploadFolder'] == null ? undefined : json['uploadFolder'],
        'thumbnailFolder': json['thumbnailFolder'] == null ? undefined : json['thumbnailFolder'],
        'publicUrl': json['publicUrl'] == null ? undefined : json['publicUrl'],
        'strategyType': json['strategyType'] == null ? undefined : json['strategyType'],
        'type': json['type'] == null ? undefined : json['type'],
    };
}

  export function StrategyRequestS3StrategyConfigToJSON(json: any): StrategyRequestS3StrategyConfig {
      return StrategyRequestS3StrategyConfigToJSONTyped(json, false);
  }

  export function StrategyRequestS3StrategyConfigToJSONTyped(value?: StrategyRequestS3StrategyConfig | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'endpoint': value['endpoint'],
        'bucketName': value['bucketName'],
        'region': value['region'],
        'accessKey': value['accessKey'],
        'secretKey': value['secretKey'],
        'uploadFolder': value['uploadFolder'],
        'thumbnailFolder': value['thumbnailFolder'],
        'publicUrl': value['publicUrl'],
        'strategyType': value['strategyType'],
        'type': value['type'],
    };
}

