/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserManageInsertRequest
 */
export interface UserManageInsertRequest {
    /**
     * 
     * @type {string}
     * @memberof UserManageInsertRequest
     */
    'email': string;
    /**
     * 
     * @type {number}
     * @memberof UserManageInsertRequest
     */
    'groupId': number;
    /**
     * 
     * @type {boolean}
     * @memberof UserManageInsertRequest
     */
    'isDefaultImagePrivate': boolean;
    /**
     * 
     * @type {string}
     * @memberof UserManageInsertRequest
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof UserManageInsertRequest
     */
    'username': string;
}

