/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserSelfPatchRequest
 */
export interface UserSelfPatchRequest {
    /**
     * 
     * @type {number}
     * @memberof UserSelfPatchRequest
     */
    'defaultAlbumId'?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UserSelfPatchRequest
     */
    'email'?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserSelfPatchRequest
     */
    'isDefaultImagePrivate'?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof UserSelfPatchRequest
     */
    'password'?: string | null;
}

