/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface UserSelfPatchRequest
 */
export interface UserSelfPatchRequest {
    /**
     * 
     * @type {number}
     * @memberof UserSelfPatchRequest
     */
    defaultAlbumId?: number | null;
    /**
     * 
     * @type {string}
     * @memberof UserSelfPatchRequest
     */
    email?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof UserSelfPatchRequest
     */
    isDefaultImagePrivate?: boolean | null;
    /**
     * 
     * @type {string}
     * @memberof UserSelfPatchRequest
     */
    password?: string | null;
}

/**
 * Check if a given object implements the UserSelfPatchRequest interface.
 */
export function instanceOfUserSelfPatchRequest(value: object): value is UserSelfPatchRequest {
    return true;
}

export function UserSelfPatchRequestFromJSON(json: any): UserSelfPatchRequest {
    return UserSelfPatchRequestFromJSONTyped(json, false);
}

export function UserSelfPatchRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): UserSelfPatchRequest {
    if (json == null) {
        return json;
    }
    return {
        
        'defaultAlbumId': json['defaultAlbumId'] == null ? undefined : json['defaultAlbumId'],
        'email': json['email'] == null ? undefined : json['email'],
        'isDefaultImagePrivate': json['isDefaultImagePrivate'] == null ? undefined : json['isDefaultImagePrivate'],
        'password': json['password'] == null ? undefined : json['password'],
    };
}

  export function UserSelfPatchRequestToJSON(json: any): UserSelfPatchRequest {
      return UserSelfPatchRequestToJSONTyped(json, false);
  }

  export function UserSelfPatchRequestToJSONTyped(value?: UserSelfPatchRequest | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'defaultAlbumId': value['defaultAlbumId'],
        'email': value['email'],
        'isDefaultImagePrivate': value['isDefaultImagePrivate'],
        'password': value['password'],
    };
}

