/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


// May contain unused imports in some cases
// @ts-ignore
import type { StrategyTypeEnum } from './strategy-type-enum';

/**
 * 
 * @export
 * @interface WebDavStrategy
 */
export interface WebDavStrategy {
    /**
     * 
     * @type {StrategyTypeEnum}
     * @memberof WebDavStrategy
     */
    'strategyType': StrategyTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof WebDavStrategy
     */
    'password': string;
    /**
     * 
     * @type {string}
     * @memberof WebDavStrategy
     */
    'serverUrl': string;
    /**
     * 
     * @type {string}
     * @memberof WebDavStrategy
     */
    'thumbnailFolder': string;
    /**
     * 
     * @type {string}
     * @memberof WebDavStrategy
     */
    'uploadFolder': string;
    /**
     * 
     * @type {string}
     * @memberof WebDavStrategy
     */
    'username': string;
}



