name: Bug Report
description: Report an error or unexpected behavior
title: "Bug: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting the issue! Please fill out the details as thoroughly as possible.

  - type: input
    id: version
    attributes:
      label: Version
      description: Specific version where the issue occurs
      placeholder: e.g. v1.2.3
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Problem Description
      description: Detailed description of the issue
      placeholder: Describe the bug clearly and concisely
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Detailed steps to recreate the issue
      placeholder: |
        1. First...
        2. Then...
        3. Finally...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Describe what you expected to happen
    validations:
      required: true
