name: Feature Request
description: Suggest a new feature or improvement
title: "Feature: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your improvement suggestion! Please describe your idea in detail.

  - type: input
    id: version
    attributes:
      label: Target Version
      description: Version you'd like this feature implemented
      placeholder: e.g. v2.0.0
    validations:
      required: false

  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: Detailed explanation of the suggested feature
      placeholder: Clearly explain the new feature or improvement
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Explain why this feature is needed
    validations:
      required: true

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any other relevant information
    validations:
      required: false

  - type: checkboxes
    id: priority
    attributes:
      label: Priority
      description: Importance of this feature
      options:
        - label: High Priority
        - label: Medium Priority
        - label: Low Priority
