ktor:
  application:
    modules:
      - io.sakurasou.ApplicationKt.mainModule
    base-url: "$BASE_URL:/"
    database:
      driver: $DATABASE_DRIVER
      url: $DATABASE_URL
      username: $DATABASE_USERNAME
      password: $DATABASE_PASSWORD
    cache:
      redis:
        host: "$REDIS_HOST:disable"
        port: "$REDIS_PORT:6379"
  deployment:
    port: 8080
    watch:
      - classes
jwt:
  secret: "MIIBVQIBADANBgkqhkiG9w0BAQEFAASCAT8wggE7AgEAAkEAtfJaLrzXILUg1U3N1KV8yJr92GHn5OtYZR7qWk1Mc4cy4JGjklYup7weMjBD9f3bBVoIsiUVX6xNcYIr0Ie0AQIDAQABAkEAg+FBquToDeYcAWBe1EaLVyC45HG60zwfG1S4S3IB+y4INz1FHuZppDjBh09jptQNd+kSMlG1LkAc/3znKTPJ7QIhANpyB0OfTK44lpH4ScJmCxjZV52mIrQcmnS3QzkxWQCDAiEA1Tn7qyoh+0rOO/9vJHP8U/beo51SiQMw0880a1UaiisCIQDNwY46EbhGeiLJR1cidr+JHl86rRwPDsolmeEF5AdzRQIgK3KXL3d0WSoS//K6iOkBX3KMRzaFXNnDl0U/XyeGMuUCIHaXv+n+Brz5BDnRbWS+2vkgIe9bUNlkiArpjWvX+2we"
  issuer: "https://sakurasou.io/"
  audience: "jwt-audience"
  realm: "ktor sample app"
