ktor:
  application:
    modules:
      - io.sakurasou.ApplicationKt.mainModule
    base-url: "$BASE_URL:/"
    database:
      driver: $DATABASE_DRIVER
      url: $DATABASE_URL
      username: $DATABASE_USERNAME
      password: $DATABASE_PASSWORD
    cache:
      redis:
        host: "$REDIS_HOST:disable"
        port: "$REDIS_PORT:6379"
  deployment:
    port: 8080
io:
  ktor:
    development: "$DEVELOPMENT:false"
jwt:
  secret: $JWT_SECRET
  issuer: $JWT_ISSUER
  audience: $JWT_AUDIENCE
  realm: $JWT_REALM
