ktor:
  application:
    modules:
      - io.sakurasou.ApplicationKt.module
    base-url: "$BASE_URL:/"
    database:
      driver: $DATABASE_DRIVER
      url: $DATABASE_URL
      username: $DATABASE_USERNAME
      password: $DATABASE_PASSWORD
    cache:
      redis:
        host: $REDIS_HOST
        port: $REDIS_PORT
  deployment:
    port: 8080
    watch:
      - classes
jwt:
  domain: "https://jwt-provider-domain/"
  audience: "jwt-audience"
  realm: "ktor sample app"
