/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  IoSakurasouControllerRequestSiteInitRequest,
} from '../models/index';
import {
    IoSakurasouControllerRequestSiteInitRequestFromJSON,
    IoSakurasouControllerRequestSiteInitRequestToJSON,
} from '../models/index';

export interface ApiComUcasoftKtorSimpleCacheCacheOutputSelector21a9a705RandomGetRequest {
    id?: string;
}

export interface ApiComUcasoftKtorSimpleCacheCacheOutputSelector4a481728SImageUniqueIdGetRequest {
    imageUniqueId: string;
}

export interface ApiSiteInitPostRequest {
    ioSakurasouControllerRequestSiteInitRequest: IoSakurasouControllerRequestSiteInitRequest;
}

/**
 * 
 */
export class DefaultApi extends runtime.BaseAPI {

    /**
     * return random image if setting allow
     */
    async apiComUcasoftKtorSimpleCacheCacheOutputSelector21a9a705RandomGetRaw(requestParameters: ApiComUcasoftKtorSimpleCacheCacheOutputSelector21a9a705RandomGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        const queryParameters: any = {};

        if (requestParameters['id'] != null) {
            queryParameters['id'] = requestParameters['id'];
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/com.ucasoft.ktor.simpleCache.CacheOutputSelector@21a9a705/random`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * return random image if setting allow
     */
    async apiComUcasoftKtorSimpleCacheCacheOutputSelector21a9a705RandomGet(requestParameters: ApiComUcasoftKtorSimpleCacheCacheOutputSelector21a9a705RandomGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiComUcasoftKtorSimpleCacheCacheOutputSelector21a9a705RandomGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiComUcasoftKtorSimpleCacheCacheOutputSelector4a481728SImageUniqueIdGetRaw(requestParameters: ApiComUcasoftKtorSimpleCacheCacheOutputSelector4a481728SImageUniqueIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['imageUniqueId'] == null) {
            throw new runtime.RequiredError(
                'imageUniqueId',
                'Required parameter "imageUniqueId" was null or undefined when calling apiComUcasoftKtorSimpleCacheCacheOutputSelector4a481728SImageUniqueIdGet().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/api/com.ucasoft.ktor.simpleCache.CacheOutputSelector@4a481728/s/{imageUniqueId}`.replace(`{${"imageUniqueId"}}`, encodeURIComponent(String(requestParameters['imageUniqueId']))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiComUcasoftKtorSimpleCacheCacheOutputSelector4a481728SImageUniqueIdGet(requestParameters: ApiComUcasoftKtorSimpleCacheCacheOutputSelector4a481728SImageUniqueIdGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiComUcasoftKtorSimpleCacheCacheOutputSelector4a481728SImageUniqueIdGetRaw(requestParameters, initOverrides);
    }

    /**
     */
    async apiSiteInitPostRaw(requestParameters: ApiSiteInitPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters['ioSakurasouControllerRequestSiteInitRequest'] == null) {
            throw new runtime.RequiredError(
                'ioSakurasouControllerRequestSiteInitRequest',
                'Required parameter "ioSakurasouControllerRequestSiteInitRequest" was null or undefined when calling apiSiteInitPost().'
            );
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/api/site/init`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: IoSakurasouControllerRequestSiteInitRequestToJSON(requestParameters['ioSakurasouControllerRequestSiteInitRequest']),
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async apiSiteInitPost(requestParameters: ApiSiteInitPostRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.apiSiteInitPostRaw(requestParameters, initOverrides);
    }

}
