/* tslint:disable */
/* eslint-disable */
/**
 * HoshizoraPics API
 * API for testing and demonstration purposes.
 *
 * The version of the OpenAPI document: latest
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  CommonResponseKotlinCollectionsListRoleVO,
} from '../models/index';
import {
    CommonResponseKotlinCollectionsListRoleVOFromJSON,
    CommonResponseKotlinCollectionsListRoleVOToJSON,
} from '../models/index';

/**
 * 
 */
export class RoleApi extends runtime.BaseAPI {

    /**
     */
    async apiRoleAllGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseKotlinCollectionsListRoleVO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/role/all`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseKotlinCollectionsListRoleVOFromJSON(jsonValue));
    }

    /**
     */
    async apiRoleAllGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseKotlinCollectionsListRoleVO> {
        const response = await this.apiRoleAllGetRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async apiRoleSelfGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<CommonResponseKotlinCollectionsListRoleVO>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("JWT", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/api/role/self`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CommonResponseKotlinCollectionsListRoleVOFromJSON(jsonValue));
    }

    /**
     */
    async apiRoleSelfGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<CommonResponseKotlinCollectionsListRoleVO> {
        const response = await this.apiRoleSelfGetRaw(initOverrides);
        return await response.value();
    }

}
